/**
 * `npm run test:groups-mountain-lists`.
 *
 * Structure plan slice S5 and risk R14: THE APP'S CATALOGUE IS NOT THE
 * SERVER'S, and group code that forgets it offers peaks that cannot be saved
 * and hides the ones that can.
 *
 * A group's `destination_id` is a foreign key into `public.destinations`, whose
 * contents are generated by `icefall-supabase/seed/catalogue.sql`. The app
 * draws its own fourteen peaks from `@/data/mock/mountains`, for pages and
 * photographs. The two lists are measured against each other here, from the
 * files themselves, so a change to either is a failing test rather than a
 * refusal somebody meets at the last tap of a create form.
 *
 * WHAT IS NOT PROVEN HERE: that the real database matches the seed file (that
 * is `tests/groups-type-trip.test.mjs`, which runs the migrations), and that
 * the picker draws what it is given (checked by hand in the browser).
 */
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import { MOUNTAINS } from "@/data/mock/mountains";
import {
  aboutForKind,
  appPeakFor,
  destinationMatches,
  sortDestinations,
  toGroupDestination,
  type GroupDestination,
} from "@/groups/mountains";

let passed = 0;
const failures: string[] = [];
const test = (name: string, fn: () => void) => {
  try {
    fn();
    passed += 1;
    console.log(`  ✓ ${name}`);
  } catch (err) {
    failures.push(name);
    console.log(`  ✗ ${name}`);
    console.log(`    ${err instanceof Error ? err.message : String(err)}`);
  }
};

const readFile = (p: string) => readFileSync(resolve(process.cwd(), p), "utf8");

/* -------------------------------------------------------------------------- */
/* The two lists, read from the files that define them                         */
/* -------------------------------------------------------------------------- */

const catalogue = readFile("../icefall-supabase/seed/catalogue.sql");

/** Every mountain row of the seed: `('id', 'Name', 'mountain', …, elevation)`. */
const serverMountains = new Map<string, { name: string; elevationM: number }>();
for (const m of catalogue.matchAll(
  /\('([a-z0-9-]+)', '((?:[^']|'')*)', 'mountain', '[^']*', '[^']*', '[^']*', (\d+)\)/g,
)) {
  serverMountains.set(m[1], { name: m[2].replace(/''/g, "'"), elevationM: Number(m[3]) });
}

const serverTreks = new Set(
  [...catalogue.matchAll(/\('([a-z0-9-]+)', '(?:[^']|'')*', 'trek',/g)].map((m) => m[1]),
);

const appIds = MOUNTAINS.map((m) => m.id);
const appOnly = appIds.filter((id) => !serverMountains.has(id));
const serverOnly = [...serverMountains.keys()].filter((id) => !appIds.includes(id));

console.log("\nGroups — the app's mountains against the server's catalogue\n");

/* -------------------------------------------------------------------------- */
/* 1. The measured difference, and it is allowed to change only on purpose      */
/* -------------------------------------------------------------------------- */

test("both lists were actually read", () => {
  assert.equal(MOUNTAINS.length, 14, "the app's catalogue has changed size");
  assert.equal(new Set(appIds).size, 14, "two app mountains share an id");
  assert.equal(serverMountains.size, 52, "the seed's mountain list has changed size");
  assert.equal(serverTreks.size, 252, "the seed's trek list has changed size");
});

test("exactly three of the app's peaks have no row on the server", () => {
  /*
   * A group filed against one of these is refused by the foreign key on
   * `groups.destination_id`. They are the reason group code reads the server's
   * list and never `MOUNTAINS`: a picker built from the app would offer all
   * three, and each would fail at the last tap.
   */
  assert.deepEqual(appOnly.sort(), ["gran-paradiso", "mount-olympus", "triglav"]);
});

test("and 41 of the server's mountains are not in the app, Ama Dablam among them", () => {
  /*
   * The plan (D6) says 38, written before this was measured; the file has 52
   * mountains and shares 11 with the app, so 41 it is. Either way the point
   * stands and is the other half of R14: a picker built from the app's
   * catalogue hides every one of these, including a peak as ordinary as Ama
   * Dablam, from somebody trying to start a group for it.
   */
  assert.equal(serverOnly.length, 41);
  assert.ok(serverOnly.includes("ama-dablam"));
  assert.equal(
    appIds.includes("ama-dablam"),
    false,
    "the app now carries Ama Dablam — update this test rather than the claim",
  );
});

test("where both lists hold a peak, they agree about how high it is", () => {
  /*
   * The lesson written at the top of the seed: two files once disagreed about
   * Ama Dablam by two metres. NAMES ARE NOT COMPARED — the app says "Everest"
   * where the catalogue says "Mount Everest", which is a display choice rather
   * than a disagreement about a fact.
   */
  for (const m of MOUNTAINS) {
    const server = serverMountains.get(m.id);
    if (!server) continue;
    assert.equal(server.elevationM, m.elevationM, `${m.id}: ${m.elevationM} vs ${server.elevationM}`);
  }
});

/* -------------------------------------------------------------------------- */
/* 2. The picker offers the server's list, and only that                       */
/* -------------------------------------------------------------------------- */

test("the catalogue reader asks the server, and never falls back to the app's peaks", () => {
  const src = readFile("src/groups/mountains.ts");
  /* The public reader serves the cache, shares one read between the rows of a
     screen, and does the asking in `readCatalogue` — which is the body that
     must never reach for the app's own peaks. */
  const door = src.slice(src.indexOf("export async function readGroupDestinations"));
  assert.match(door.slice(0, door.indexOf("\n}")), /readCatalogue\(\)/);
  const read = src.slice(src.indexOf("async function readCatalogue"));
  const body = read.slice(0, read.indexOf("\n}"));
  assert.match(body, /\.from\("destinations"\)/);
  assert.match(body, /\.in\("kind", \["mountain", "trek"\]\)/);
  assert.equal(/MOUNTAINS/.test(body), false, "the server read reaches for the app's catalogue");
  // The app's list is used in exactly one place, and it is a lookup for a
  // photograph and a mountain page — never a source of options. Comments are
  // stripped first: this file explains the rule at length, and a mention of
  // the name in prose is not a use of it.
  const code = src.replace(/\/\*[\s\S]*?\*\//g, "").replace(/^\s*\/\/.*$/gm, "");
  const uses = code.match(/MOUNTAINS/g) ?? [];
  assert.equal(uses.length, 2, `MOUNTAINS is used ${uses.length} times, not just the import and appPeakFor`);
  const lookup = src.slice(src.indexOf("export function appPeakFor"));
  assert.match(lookup.slice(0, lookup.indexOf("\n}")), /MOUNTAINS\.find/);
});

test("the create picker is handed the server catalogue, and its rows come from that", () => {
  const groups = readFile("src/screens/explore/Groups.tsx");
  const create = groups.slice(
    groups.indexOf("function CreateGroupCard"),
    groups.indexOf("/* ---- The form ---"),
  );
  assert.match(create, /catalogue=\{catalogue\}/);
  assert.match(create, /onPickDestination=\{\(picked\)/);
  assert.match(create, /useGroupDestinations\(\)/);
  // The create flow must not build options out of the app's fourteen peaks.
  assert.equal(/MOUNTAINS/.test(create), false, "the create card reads the app's catalogue");

  const list = groups.slice(groups.indexOf("function CatalogueList"), groups.indexOf("/**\n * The picker, in its two modes."));
  assert.match(list, /matches\.map\(\(destination\)/);
  assert.equal(/MOUNTAINS\.filter/.test(list), false);
});

test("an app-only peak cannot reach the picker, because the server has no such row", () => {
  // The rows offered are whatever `destinations` returned. These three are not
  // in it, so no answer the server can give contains them.
  for (const id of appOnly) {
    assert.equal(serverMountains.has(id), false);
    assert.equal(serverTreks.has(id), false);
  }
});

/* -------------------------------------------------------------------------- */
/* 3. The reader itself                                                        */
/* -------------------------------------------------------------------------- */

const row = (over: Record<string, unknown> = {}) => ({
  id: "ama-dablam",
  name: "Ama Dablam",
  kind: "mountain",
  range: "Mahalangur Himal",
  region: "Himalaya & Asia",
  country: "Nepal",
  elevation_m: 6814,
  ...over,
});

test("a row is read as it is, with nothing filled in", () => {
  const d = toGroupDestination(row());
  assert.deepEqual(d, {
    id: "ama-dablam",
    name: "Ama Dablam",
    kind: "mountain",
    range: "Mahalangur Himal",
    region: "Himalaya & Asia",
    country: "Nepal",
    elevationM: 6814,
  });
});

test("a trek comes back as a trek, with no elevation", () => {
  const d = toGroupDestination(
    row({ id: "tour-du-mont-blanc", name: "Tour du Mont Blanc", kind: "trek", elevation_m: null, range: null }),
  );
  assert.equal(d?.kind, "trek");
  assert.equal(d?.elevationM, null);
  assert.equal(d?.range, null);
});

test("a row with no id, no name or an unknown kind is dropped rather than guessed at", () => {
  assert.equal(toGroupDestination(row({ id: null })), null);
  assert.equal(toGroupDestination(row({ name: "  " })), null);
  assert.equal(toGroupDestination(row({ kind: "region" })), null);
  assert.equal(toGroupDestination(null), null);
  assert.equal(toGroupDestination("ama-dablam"), null);
});

test("a search matches the name, the range, the region and the country", () => {
  const d = toGroupDestination(row()) as GroupDestination;
  for (const q of ["ama", "AMA DAB", "mahalangur", "nepal", "himalaya", ""]) {
    assert.equal(destinationMatches(d, q), true, q);
  }
  assert.equal(destinationMatches(d, "chamonix"), false);
});

test("mountains come before treks, and each list is alphabetical", () => {
  const list = [
    toGroupDestination(row({ id: "b-trek", name: "B Trek", kind: "trek" })),
    toGroupDestination(row({ id: "matterhorn", name: "Matterhorn" })),
    toGroupDestination(row({ id: "a-trek", name: "A Trek", kind: "trek" })),
    toGroupDestination(row({ id: "eiger", name: "Eiger" })),
  ].filter((d): d is GroupDestination => d !== null);
  assert.deepEqual(
    sortDestinations(list).map((d) => d.id),
    ["eiger", "matterhorn", "a-trek", "b-trek"],
  );
});

test("a group filed against a trek is about a trek, and never called a mountain", () => {
  assert.equal(aboutForKind("mountain"), "mountain");
  assert.equal(aboutForKind("trek"), "trek");
});

test("the app's record is found for a peak it holds, and is absent rather than invented for one it does not", () => {
  assert.equal(appPeakFor("mont-blanc")?.name, "Mont Blanc");
  assert.equal(appPeakFor("ama-dablam"), null);
  assert.equal(appPeakFor(null), null);
  assert.equal(appPeakFor("tour-du-mont-blanc"), null);
});

console.log(`\n${passed} passed, ${failures.length} failed`);
if (failures.length > 0) {
  for (const f of failures) console.log(`  - ${f}`);
  process.exitCode = 1;
}
