/**
 * LOCAL DAYS, DONE ONCE.
 *
 * Constitution §2, one of only two engineering rules with teeth:
 *
 *   > Never `new Date("YYYY-MM-DD")` for a local day — it parses as UTC midnight
 *   > and shifts a day west of Greenwich. Use the existing `parseDay` helpers.
 *   > This bug has been fixed several times already.
 *
 * It is worth being precise about what breaks, because it is not obvious and it
 * is not cosmetic. `new Date("2026-10-04")` is **2026-10-04T00:00:00Z**. On a
 * machine in UTC−8 that instant is 2026-10-03 at 16:00 local. So from four in
 * the afternoon on the 3rd, any `expiry < now` test says the document has
 * expired — and in this app that test is what hides a guide's listing. A guide in
 * California loses a day of work off the end of every certificate they hold.
 *
 * The same shift, pointed the other way, decides whether a departure is "today"
 * and therefore whether their money is released.
 *
 * TWO HELPERS, AND THE DISTINCTION BETWEEN THEM IS THE WHOLE POINT:
 *
 *   · `parseDay` turns a CALENDAR DAY ("2026-10-04") into local midnight on that
 *     day. Use it for anything a human wrote on a certificate or picked from a
 *     calendar — an expiry, the start and end of an opening.
 *   · `startOfDay` collapses an INSTANT to local midnight, so a day-versus-now
 *     comparison asks "is this day past?" rather than "is this moment past?".
 *     Without it, a trip that ends today drops out of "current" at 00:01.
 *
 * A timestamp — a message arriving, a booking being made — is an instant and
 * needs neither. Pass those to `new Date()` directly; they carry their offset.
 */

/**
 * A calendar day string → local midnight on that day, or NULL if it is not one.
 *
 * IT RETURNS NULL RATHER THAN AN `Invalid Date`, AND THAT IS THE WHOLE POINT.
 *
 * The previous version returned whatever `new Date` gave it. Fed anything that
 * is not `YYYY-MM-DD` — a display string like "31 Dec 2028", an empty field, a
 * `2026/10/04` — it produced an `Invalid Date`, and:
 *
 *     new Date(NaN) < new Date()   ===   false
 *
 * Every comparison against an unreadable date answers "no". So the expiry check
 * that hides a guide's listing would have said **NOT EXPIRED** for every value it
 * could not read. A guide whose liability insurance had genuinely lapsed would
 * have stayed live to clients, silently, with nothing in the console — and the
 * whole reason that check exists is the case where the data is wrong.
 *
 * Measured, not reasoned about: all five malformed inputs tested returned
 * `Invalid Date` and compared as not-expired.
 *
 * A SAFETY TEST THAT CANNOT READ ITS INPUT MUST NOT ANSWER "SAFE". Null forces
 * every caller to say what it does about that, which is why this signature is
 * awkward on purpose — see `hasExpired`, which is where the decision is made
 * once.
 *
 * This cannot bite today: every date in this app is generated by `dayOffset`
 * below. It becomes reachable the moment a date arrives from the database or a
 * hand-edited fixture, which is exactly when a safety check matters.
 */
export function parseDay(iso: string | null | undefined): Date | null {
  if (typeof iso !== "string") return null;
  const m = /^(\d{4})-(\d{2})-(\d{2})/.exec(iso);
  if (!m) return null;
  const [y, mo, d] = [Number(m[1]), Number(m[2]), Number(m[3])];
  const at = new Date(y, mo - 1, d);
  // Rejects 2026-02-31 and friends, which JS would silently roll into March.
  if (at.getFullYear() !== y || at.getMonth() !== mo - 1 || at.getDate() !== d) return null;
  return at;
}

/**
 * Has this calendar day passed? Unreadable counts as YES.
 *
 * The single place the lapse decision is made, so no screen can reach its own
 * conclusion about a date it could not parse.
 *
 * THE LAST DAY IS INCLUSIVE. A certificate expiring on the 4th is valid all of
 * the 4th and lapses on the 5th — which is what "expires on the 4th" means to
 * the person holding it, and what the app tells them in words.
 *
 * AN UNREADABLE DATE RETURNS TRUE, and the asymmetry is the argument: treating
 * it as valid leaves a client with a guide whose cover may have lapsed, on
 * glaciated ground, and nobody ever finds out. Treating it as expired hides a
 * listing the guide can restore by sending the document again. One error is
 * recoverable by the person harmed; the other is not. Callers that want to TELL
 * the guide which of the two happened ask `parseDay` for null themselves.
 */
export function hasExpired(day: string | null | undefined, now: Date = new Date()): boolean {
  const on = parseDay(day);
  if (on === null) return true;
  return on < startOfDay(now);
}

/** Whole local days from today until `day`, or null if it cannot be read. */
export function daysUntil(day: string | null | undefined, now: Date = new Date()): number | null {
  const on = parseDay(day);
  if (on === null) return null;
  return Math.round((on.getTime() - startOfDay(now).getTime()) / 86_400_000);
}

/** An instant → local midnight of the day it falls in. */
export function startOfDay(at: Date): Date {
  return new Date(at.getFullYear(), at.getMonth(), at.getDate());
}

/** A local day, `n` days from `from`, as "YYYY-MM-DD". */
export function dayOffset(from: Date, n: number): string {
  const d = new Date(from.getFullYear(), from.getMonth(), from.getDate() + n);
  const p = (x: number) => String(x).padStart(2, "0");
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}`;
}

/**
 * A local day, `n` days from `from`, as an unambiguous ISO INSTANT at local
 * midday.
 *
 * Midday rather than midnight, and that is not arbitrary: the shared money model
 * takes `departureIso` and does `new Date(departureIso) <= now` to decide whether
 * a payout releases. That file belongs to Session 03 and must not be edited
 * here, so the fix is to hand it a value it cannot misread. Local midday
 * round-trips through `toISOString()` and back to the same instant, and formats
 * back to the same local day in every timezone on earth — a bare day string does
 * neither.
 */
export function middayOffset(from: Date, n: number): string {
  return new Date(from.getFullYear(), from.getMonth(), from.getDate() + n, 12).toISOString();
}
