import { useEffect, useMemo, useState } from "react";
import { Link, useLocation, useSearchParams } from "react-router-dom";
import { Check, LifeBuoy, Loader2, Send } from "lucide-react";
import { Group, SettingsPage } from "@/components/settings/kit";
import { AzureNotice, Button, Card, Disclaimer, SectionLabel } from "@/components/ui/primitives";
import { Rise } from "@/components/layout/chrome";
import { supabase } from "@/backend/client";
import { useOnline } from "@/lib/useOnline";
import {
  MIN_BODY_CHARS,
  MAX_SUBJECT_CHARS,
  SUPPORT_ABUSE_IS_SEPARATE,
  SUPPORT_NO_BACKEND,
  SUPPORT_NO_RESPONSE_TIME,
  SUPPORT_NOT_SENT,
  SUPPORT_SIGNED_OUT,
  SUPPORT_STORED_NOTICE,
  SUPPORT_TYPES,
  openSupportTicket,
  type SupportType,
} from "@/support/tickets";

/**
 * Contact support — the screen that replaced three dead `mailto:` links.
 *
 * WHAT IT WILL NOT DO, IN ORDER OF HOW BADLY IT WOULD BREAK THE PRODUCT
 *
 *   It will not say "sent" without a reference. The reference is generated by
 *   the database on insert, so holding one is the only proof the request was
 *   stored rather than merely typed. There is no optimistic success here.
 *
 *   It will not queue anything. Offline, it says so and keeps the words on
 *   screen. A silent retry queue would let somebody walk away from a safety
 *   problem believing it had been reported.
 *
 *   It will not promise a reply time, and there is no soft version of that. See
 *   `SUPPORT_NO_RESPONSE_TIME`.
 *
 *   It will not ask who they are. The database derives that from the session —
 *   a chooser here would be a field somebody could answer wrongly, and the
 *   wrong answer routes a climber's problem into an operator queue.
 *
 * THE SIGNED-OUT CASE IS A DIFFERENT SCREEN, NOT A DISABLED BUTTON. The RPC's
 * `execute` is granted to `authenticated` only, so an anonymous call is refused
 * before the function runs and returns `permission denied for function
 * open_support_ticket`. Rendering the form and letting somebody write six
 * paragraphs into it before meeting that is the cruel version. It is checked
 * first.
 */

type Gate =
  | { state: "checking" }
  | { state: "no-backend" }
  | { state: "signed-out" }
  | { state: "ready" };

/**
 * The unsent draft, on this device only.
 *
 * A DRAFT IS NOT A QUEUE, and the distinction is the whole point. A queue
 * implies "we will send this for you", which is the thing this screen must
 * never imply — somebody would walk away from a safety problem believing it had
 * been reported. This is the text still sitting in the box, kept across a trip
 * to the sign-in screen and back, and it says so where it is offered.
 *
 * `sessionStorage`, not `localStorage`: it belongs to this tab and this visit.
 * A half-written complaint should not still be here next week, and it must
 * never outlive the person's session on a shared device.
 */
const DRAFT_KEY = "icefall.support.draft.v1";

type Draft = { type: string; subject: string; body: string };

function readDraft(): Draft | null {
  try {
    const raw = sessionStorage.getItem(DRAFT_KEY);
    if (!raw) return null;
    const d = JSON.parse(raw) as Partial<Draft>;
    if (typeof d.subject !== "string" || typeof d.body !== "string") return null;
    return { type: String(d.type ?? ""), subject: d.subject, body: d.body };
  } catch {
    // Private mode, or somebody else's JSON. An unreadable draft is no draft.
    return null;
  }
}

function writeDraft(d: Draft): void {
  try {
    if (!d.subject.trim() && !d.body.trim()) {
      sessionStorage.removeItem(DRAFT_KEY);
      return;
    }
    sessionStorage.setItem(DRAFT_KEY, JSON.stringify(d));
  } catch {
    /* Storage full or blocked. The words are still on screen; that is enough. */
  }
}

function clearDraft(): void {
  try {
    sessionStorage.removeItem(DRAFT_KEY);
  } catch {
    /* nothing to do, and nothing depends on it */
  }
}

export default function SupportRequest() {
  const [params] = useSearchParams();
  const location = useLocation();
  const online = useOnline();

  const initialType = useMemo<SupportType>(() => {
    const t = params.get("type");
    return SUPPORT_TYPES.some((o) => o.value === t) ? (t as SupportType) : "account";
  }, [params]);

  const restored = useMemo(readDraft, []);

  const [gate, setGate] = useState<Gate>({ state: "checking" });
  const [type, setType] = useState<SupportType>(() =>
    restored && SUPPORT_TYPES.some((o) => o.value === restored.type)
      ? (restored.type as SupportType)
      : initialType,
  );
  const [subject, setSubject] = useState(restored?.subject ?? "");
  const [body, setBody] = useState(restored?.body ?? "");
  const [sending, setSending] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [needsSignIn, setNeedsSignIn] = useState(false);
  const [sent, setSent] = useState<{ reference: string } | null>(null);

  useEffect(() => {
    let alive = true;
    async function check() {
      if (!supabase) {
        if (alive) setGate({ state: "no-backend" });
        return;
      }
      const { data } = await supabase.auth.getSession();
      if (!alive) return;
      setGate({ state: data.session ? "ready" : "signed-out" });
    }
    void check();
    return () => {
      alive = false;
    };
  }, []);

  // Kept in step with the boxes, so a trip to sign-in and back returns the
  // words rather than an empty form. Never sent by this effect — see DRAFT_KEY.
  useEffect(() => {
    writeDraft({ type, subject, body });
  }, [type, subject, body]);

  const bodyShort = body.trim().length < MIN_BODY_CHARS;
  const canSend = !sending && subject.trim().length > 0 && !bodyShort;

  async function send() {
    setSending(true);
    setError(null);
    const result = await openSupportTicket({
      subject,
      body,
      type,
      // Where they were, for triage. Never read as what they asked for.
      originScreen: location.pathname + location.search,
    });
    setSending(false);
    if (result.ok) {
      clearDraft();
      setSent({ reference: result.reference });
      return;
    }
    /**
     * THE GATE IS NOT RE-RAISED HERE, AND THAT IS A FIX RATHER THAN AN
     * OVERSIGHT. Swapping back to the signed-out screen on a failed send threw
     * away everything they had typed — caught in the browser, having written a
     * paragraph and watched it vanish. The gate is the right screen for
     * somebody who arrives with nothing written; it is the wrong screen for
     * somebody who has just written. The error goes inline, the form stays, and
     * the words stay in it.
     */
    setError(result.message);
    setNeedsSignIn(result.reason === "signed-out");
  }

  /* ---- Stored ----------------------------------------------------------- */

  if (sent) {
    return (
      <SettingsPage title="Request sent" subtitle="It is stored." back="/settings/support">
        <Rise className="pt-5">
          <Card className="border-summit/30 bg-summit/[0.04]">
            <div className="flex items-start gap-3">
              <Check size={18} strokeWidth={2} className="mt-px shrink-0 text-summit" />
              <div className="min-w-0">
                <p className="text-[13.5px] text-snow">Your reference</p>
                {/* The evidence, drawn as the largest thing on the screen. */}
                <p className="tnum mt-1.5 text-[24px] font-light tracking-[0.06em] text-snow">
                  {sent.reference}
                </p>
              </div>
            </div>
          </Card>
        </Rise>

        <Rise className="pt-4">
          <Disclaimer>{SUPPORT_STORED_NOTICE}</Disclaimer>
        </Rise>

        <Rise className="pt-3">
          <Disclaimer>{SUPPORT_NO_RESPONSE_TIME}</Disclaimer>
        </Rise>

        <Rise className="pt-6">
          <Button asChild variant="secondary" className="w-full">
            <Link to="/settings/support">Back to help</Link>
          </Button>
        </Rise>
      </SettingsPage>
    );
  }

  /* ---- Cannot send at all ----------------------------------------------- */

  if (gate.state === "checking") {
    return (
      <SettingsPage title="Contact support" back="/settings/support">
        <Rise className="pt-6">
          <div className="flex items-center gap-2.5 text-[12.5px] text-mist-dim">
            <Loader2 size={14} strokeWidth={1.8} className="animate-spin" />
            Checking your account…
          </div>
        </Rise>
      </SettingsPage>
    );
  }

  if (gate.state === "no-backend" || gate.state === "signed-out") {
    const isSignedOut = gate.state === "signed-out";
    return (
      <SettingsPage title="Contact support" back="/settings/support">
        <Rise className="pt-5">
          <AzureNotice title={isSignedOut ? "Sign in to send this" : "Not connected"}>
            <p>{isSignedOut ? SUPPORT_SIGNED_OUT : SUPPORT_NO_BACKEND}</p>
          </AzureNotice>
        </Rise>

        {isSignedOut && (
          <Rise className="pt-4">
            <Button asChild className="w-full">
              <Link to="/auth/signin">Sign in</Link>
            </Button>
          </Rise>
        )}

        <Rise className="pt-4">
          <Disclaimer>{SUPPORT_NO_RESPONSE_TIME}</Disclaimer>
        </Rise>
      </SettingsPage>
    );
  }

  /* ---- The form --------------------------------------------------------- */

  return (
    <SettingsPage
      title="Contact support"
      subtitle="One desk. It reaches a person, not a mailbox."
      back="/settings/support"
    >
      <Group label="What is this about?">
        {/* A chooser for the SUBJECT of the problem — never for who is asking.
            The database derives the requester from the session. */}
        <div className="px-4 py-3.5">
          <div className="flex flex-wrap gap-2">
            {SUPPORT_TYPES.map((o) => (
              <button
                key={o.value}
                type="button"
                onClick={() => setType(o.value)}
                className={
                  type === o.value
                    ? "rounded-pill border border-azure/55 bg-azure/[0.12] px-3 py-1.5 text-[12px] text-azure transition-colors"
                    : "rounded-pill border border-hairline-strong px-3 py-1.5 text-[12px] text-mist transition-colors hover:text-snow"
                }
              >
                {o.label}
              </button>
            ))}
          </div>
          <p className="mt-3 text-[11px] leading-relaxed text-mist-dim">
            {SUPPORT_TYPES.find((o) => o.value === type)?.detail}
          </p>
        </div>
      </Group>

      <Rise className="pt-5">
        <SectionLabel>Subject</SectionLabel>
        <input
          value={subject}
          onChange={(e) => setSubject(e.target.value.slice(0, MAX_SUBJECT_CHARS))}
          placeholder="One line — what has gone wrong"
          className="mt-3 w-full rounded-card border border-hairline bg-graphite px-4 py-3 text-[13.5px] text-snow outline-none placeholder:text-mist-dim focus:border-azure/50"
        />
      </Rise>

      <Rise className="pt-5">
        <SectionLabel>What happened</SectionLabel>
        <textarea
          value={body}
          onChange={(e) => setBody(e.target.value)}
          rows={10}
          placeholder="What you were doing, what you expected, and what happened instead."
          className="mt-3 w-full resize-none rounded-card border border-hairline bg-graphite p-4 text-[13px] leading-relaxed text-snow outline-none placeholder:text-mist-dim focus:border-azure/50"
        />
        {/* States the requirement rather than counting down at somebody. */}
        <p className="mt-2 text-[11px] leading-relaxed text-mist-dim">
          {bodyShort
            ? `At least ${MIN_BODY_CHARS} characters — enough that somebody reading it can act on it.`
            : "Include anything you would want to be asked for."}
        </p>
      </Rise>

      {!online && (
        <Rise className="pt-4">
          <Disclaimer>{SUPPORT_NOT_SENT}</Disclaimer>
        </Rise>
      )}

      {error && (
        <Rise className="pt-4">
          <Card className="border-danger/30 bg-danger/[0.05]">
            <p className="text-[12.5px] leading-relaxed text-snow/85">{error}</p>
            {needsSignIn && (
              <>
                <Button asChild variant="secondary" size="sm" className="mt-3.5">
                  <Link to="/auth/signin">Sign in</Link>
                </Button>
                {/* Said out loud because it is the difference between coming
                    back to your words and coming back to an empty box. */}
                <p className="mt-2.5 text-[11px] leading-relaxed text-mist-dim">
                  What you have written is kept on this device while you sign in, and comes back
                  with you. It has not been sent to anybody.
                </p>
              </>
            )}
          </Card>
        </Rise>
      )}

      <Rise className="pt-5">
        <Button className="w-full" onClick={() => void send()} disabled={!canSend}>
          {sending ? (
            <>
              <Loader2 size={15} strokeWidth={1.8} className="animate-spin" />
              Sending
            </>
          ) : (
            <>
              <Send size={15} strokeWidth={1.8} />
              Send to support
            </>
          )}
        </Button>
      </Rise>

      <Rise className="pt-4">
        <Disclaimer>{SUPPORT_NO_RESPONSE_TIME}</Disclaimer>
      </Rise>

      <Rise className="pt-3">
        <Disclaimer>{SUPPORT_ABUSE_IS_SEPARATE}</Disclaimer>
      </Rise>

      <Rise className="pt-6">
        <div className="flex items-center gap-2.5 text-[11px] text-mist-dim">
          <LifeBuoy size={13} strokeWidth={1.7} className="shrink-0" />
          Sent from the phone app.
        </div>
      </Rise>
    </SettingsPage>
  );
}
