/**
 * The Visibility Index for every listing — the ONLY per-listing number we keep.
 *
 * GENERATED from Featured-Slot-Pricing-Framework.docx v1.0 (30 August 2026),
 * 77 mountains and 76 treks. Every price in the framework's rate card is
 * DERIVED from these numbers plus the formula in `slotPricing.ts` — verified by
 * regenerating all 613 published prices and comparing: zero mismatches.
 *
 * WHICH IS WHY THE RATE CARD IS NOT STORED HERE. Copying 613 prices in would
 * create a second source of truth that silently disagrees with the formula the
 * moment somebody edits one Index. §13 of the framework says these Indices are
 * "a first position to be corrected, not findings", and quarterly review will
 * move them. A stored price table would survive that edit unchanged and be wrong.
 *
 * The Index answers one question: how much is a Featured slot here worth
 * compared with the same slot on Everest? Built from trip price
 * (square-root compressed), client volume, and — the strongest signal —
 * operator competition. That last input is why Kilimanjaro (0.42) sits above
 * K2 (0.38) on a tenth of the trip price: Kilimanjaro operators fight for
 * customers and already buy placement, K2 operators get business by reputation.
 */

export interface Listing {
  name: string;
  /** 0.04 - 1.00, relative to Everest. */
  index: number;
  /** Treks only. CONTEXT for a sales conversation, never an input to the price. */
  refPriceEur?: number;
}

export const MOUNTAINS: readonly Listing[] = [
  { name: "Everest", index: 1.0 },
  { name: "Manaslu", index: 0.52 },
  { name: "Ama Dablam", index: 0.46 },
  { name: "Cho Oyu", index: 0.44 },
  { name: "Lhotse", index: 0.4 },
  { name: "K2", index: 0.38 },
  { name: "Shishapangma", index: 0.26 },
  { name: "Makalu", index: 0.26 },
  { name: "Dhaulagiri", index: 0.24 },
  { name: "Kangchenjunga", index: 0.24 },
  { name: "Broad Peak", index: 0.24 },
  { name: "Gasherbrum II", index: 0.24 },
  { name: "Annapurna I", index: 0.22 },
  { name: "Gasherbrum I", index: 0.2 },
  { name: "Nanga Parbat", index: 0.2 },
  { name: "Kilimanjaro", index: 0.42 },
  { name: "Vinson Massif", index: 0.4 },
  { name: "Denali", index: 0.36 },
  { name: "Aconcagua", index: 0.34 },
  { name: "Elbrus", index: 0.22 },
  { name: "Carstensz Pyramid", index: 0.22 },
  { name: "Mount Kosciuszko", index: 0.04 },
  { name: "Island Peak (Imja Tse)", index: 0.24 },
  { name: "Mera Peak", index: 0.22 },
  { name: "Lobuche East", index: 0.16 },
  { name: "Baruntse", index: 0.16 },
  { name: "Pumori", index: 0.14 },
  { name: "Himlung Himal", index: 0.14 },
  { name: "Chulu West", index: 0.1 },
  { name: "Putha Hiunchuli", index: 0.08 },
  { name: "Mont Blanc", index: 0.3 },
  { name: "Matterhorn", index: 0.26 },
  { name: "Eiger", index: 0.16 },
  { name: "Monte Rosa / Dufourspitze", index: 0.14 },
  { name: "Gran Paradiso", index: 0.14 },
  { name: "Grossglockner", index: 0.12 },
  { name: "Jungfrau", index: 0.1 },
  { name: "Weisshorn", index: 0.08 },
  { name: "Breithorn", index: 0.08 },
  { name: "Mount Olympus", index: 0.06 },
  { name: "Mount Rainier", index: 0.24 },
  { name: "Grand Teton", index: 0.14 },
  { name: "Mount Baker", index: 0.14 },
  { name: "Mount Shasta", index: 0.12 },
  { name: "Pico de Orizaba", index: 0.12 },
  { name: "Mount Hood", index: 0.1 },
  { name: "Mount Whitney", index: 0.08 },
  { name: "Iztaccihuatl", index: 0.08 },
  { name: "Ojos del Salado", index: 0.14 },
  { name: "Alpamayo", index: 0.14 },
  { name: "Chimborazo", index: 0.12 },
  { name: "Cotopaxi", index: 0.12 },
  { name: "Huayna Potosi", index: 0.1 },
  { name: "Illimani", index: 0.1 },
  { name: "Cayambe", index: 0.08 },
  { name: "Tocllaraju", index: 0.08 },
  { name: "Nevado Pisco", index: 0.08 },
  { name: "Muztagh Ata", index: 0.14 },
  { name: "Lenin Peak", index: 0.14 },
  { name: "Khan Tengri", index: 0.12 },
  { name: "Mount Ararat", index: 0.12 },
  { name: "Mount Kazbek", index: 0.1 },
  { name: "Damavand", index: 0.1 },
  { name: "Peak Korzhenevskaya", index: 0.08 },
  { name: "Ismoil Somoni Peak", index: 0.08 },
  { name: "Mount Kenya (Batian/Nelion)", index: 0.14 },
  { name: "Aoraki / Mount Cook", index: 0.16 },
  { name: "Mount Meru", index: 0.1 },
  { name: "Margherita Peak (Rwenzori)", index: 0.1 },
  { name: "Mount Toubkal", index: 0.1 },
  { name: "Mount Fuji", index: 0.1 },
  { name: "Mount Kinabalu", index: 0.1 },
  { name: "Mount Rinjani", index: 0.1 },
  { name: "Gunnbjorn Fjeld", index: 0.1 },
  { name: "Stok Kangri", index: 0.08 },
  { name: "Kang Yatse", index: 0.06 },
  { name: "Mount Sidley", index: 0.06 },
];

export const TREKS: readonly Listing[] = [
  { name: "Everest Base Camp", index: 0.48, refPriceEur: 1600 },
  { name: "Annapurna Circuit", index: 0.36, refPriceEur: 1300 },
  { name: "Annapurna Base Camp", index: 0.34, refPriceEur: 1000 },
  { name: "Gokyo Lakes", index: 0.24, refPriceEur: 1400 },
  { name: "Manaslu Circuit", index: 0.24, refPriceEur: 1500 },
  { name: "Everest Three Passes", index: 0.22, refPriceEur: 1900 },
  { name: "Ghorepani / Poon Hill", index: 0.2, refPriceEur: 600 },
  { name: "Langtang Valley", index: 0.2, refPriceEur: 900 },
  { name: "Upper Mustang", index: 0.18, refPriceEur: 2400 },
  { name: "Kanchenjunga Base Camp", index: 0.14, refPriceEur: 2600 },
  { name: "Makalu Base Camp", index: 0.12, refPriceEur: 2400 },
  { name: "Tsum Valley", index: 0.1, refPriceEur: 1800 },
  { name: "Nar Phu Valley", index: 0.1, refPriceEur: 1700 },
  { name: "K2 Base Camp & Concordia", index: 0.26, refPriceEur: 3200 },
  { name: "Snowman Trek", index: 0.2, refPriceEur: 7500 },
  { name: "Fairy Meadows / Nanga Parbat BC", index: 0.14, refPriceEur: 1400 },
  { name: "Markha Valley", index: 0.14, refPriceEur: 1000 },
  { name: "Chadar Trek", index: 0.12, refPriceEur: 1400 },
  { name: "Kashmir Great Lakes", index: 0.12, refPriceEur: 700 },
  { name: "Druk Path", index: 0.12, refPriceEur: 1600 },
  { name: "Jomolhari Trek", index: 0.12, refPriceEur: 2600 },
  { name: "Snow Lake / Hispar La", index: 0.1, refPriceEur: 4000 },
  { name: "Roopkund", index: 0.1, refPriceEur: 400 },
  { name: "Hampta Pass", index: 0.1, refPriceEur: 350 },
  { name: "Valley of Flowers", index: 0.1, refPriceEur: 450 },
  { name: "Goecha La", index: 0.1, refPriceEur: 700 },
  { name: "Sandakphu", index: 0.08, refPriceEur: 500 },
  { name: "Tour du Mont Blanc", index: 0.34, refPriceEur: 1800 },
  { name: "Walker's Haute Route", index: 0.26, refPriceEur: 2200 },
  { name: "Alta Via 1 (Dolomites)", index: 0.22, refPriceEur: 1500 },
  { name: "Camino de Santiago (Frances)", index: 0.2, refPriceEur: 1200 },
  { name: "Laugavegur (Iceland)", index: 0.18, refPriceEur: 1400 },
  { name: "GR20 (Corsica)", index: 0.16, refPriceEur: 1300 },
  { name: "Alta Via 2 (Dolomites)", index: 0.14, refPriceEur: 1700 },
  { name: "Tour du Monte Rosa", index: 0.14, refPriceEur: 2000 },
  { name: "Peaks of the Balkans", index: 0.14, refPriceEur: 1100 },
  { name: "Kungsleden", index: 0.12, refPriceEur: 1600 },
  { name: "West Highland Way", index: 0.12, refPriceEur: 800 },
  { name: "Julian Alps / Triglav", index: 0.12, refPriceEur: 900 },
  { name: "Tatra High Route", index: 0.08, refPriceEur: 700 },
  { name: "Rota Vicentina", index: 0.08, refPriceEur: 900 },
  { name: "Inca Trail", index: 0.4, refPriceEur: 800 },
  { name: "Torres del Paine (W / O Circuit)", index: 0.32, refPriceEur: 1900 },
  { name: "Salkantay", index: 0.28, refPriceEur: 600 },
  { name: "Cordillera Huayhuash Circuit", index: 0.24, refPriceEur: 1300 },
  { name: "Fitz Roy / El Chalten", index: 0.2, refPriceEur: 900 },
  { name: "Santa Cruz Trek", index: 0.18, refPriceEur: 500 },
  { name: "Choquequirao", index: 0.16, refPriceEur: 700 },
  { name: "Ausangate", index: 0.16, refPriceEur: 700 },
  { name: "Ciudad Perdida", index: 0.16, refPriceEur: 400 },
  { name: "Mount Roraima", index: 0.12, refPriceEur: 700 },
  { name: "Quilotoa Loop", index: 0.1, refPriceEur: 350 },
  { name: "John Muir Trail", index: 0.2, refPriceEur: 2600 },
  { name: "Grand Canyon Rim-to-Rim", index: 0.16, refPriceEur: 1400 },
  { name: "Wonderland Trail", index: 0.12, refPriceEur: 2200 },
  { name: "Teton Crest Trail", index: 0.12, refPriceEur: 1600 },
  { name: "West Coast Trail", index: 0.12, refPriceEur: 1500 },
  { name: "Appalachian Trail (guided sections)", index: 0.1, refPriceEur: 1500 },
  { name: "Pacific Crest Trail (guided sections)", index: 0.1, refPriceEur: 1800 },
  { name: "Zion Narrows", index: 0.1, refPriceEur: 800 },
  { name: "Chilkoot Trail", index: 0.08, refPriceEur: 1200 },
  { name: "Milford Track", index: 0.2, refPriceEur: 2000 },
  { name: "Overland Track", index: 0.16, refPriceEur: 2400 },
  { name: "Kumano Kodo", index: 0.16, refPriceEur: 1800 },
  { name: "Routeburn Track", index: 0.14, refPriceEur: 1500 },
  { name: "Nakasendo Way", index: 0.14, refPriceEur: 1900 },
  { name: "Mount Rinjani Trek", index: 0.14, refPriceEur: 300 },
  { name: "Tongariro Northern Circuit", index: 0.12, refPriceEur: 900 },
  { name: "Larapinta Trail", index: 0.12, refPriceEur: 2600 },
  { name: "Ha Giang Loop / Sapa", index: 0.12, refPriceEur: 400 },
  { name: "Mount Bromo / Ijen", index: 0.1, refPriceEur: 250 },
  { name: "Jeju Olle", index: 0.06, refPriceEur: 600 },
  { name: "Rwenzori Central Circuit", index: 0.14, refPriceEur: 2400 },
  { name: "Simien Mountains", index: 0.12, refPriceEur: 1300 },
  { name: "Atlas / Toubkal Circuit", index: 0.12, refPriceEur: 700 },
  { name: "Mount Kenya Circuit", index: 0.12, refPriceEur: 1200 },
];
