import type { ReactNode } from "react";
import { cn } from "@/lib/utils";

/**
 * The two pieces this app needs that the athlete app does not.
 *
 * Everything else — Card, Button, Badge, SectionLabel, Screen, Rise — is the
 * shared ICEFALL design system, copied verbatim so the two apps cannot drift.
 */

export type NoticeTone = "neutral" | "azure" | "summit" | "alert" | "danger";

/**
 * NEVER BUILD A CLASS NAME FROM A VARIABLE. Write every one out in full.
 *
 * The map below is deliberately five explicit lines rather than the obvious
 * `border-${tone}/40`. Tailwind scans SOURCE TEXT for class names — it never
 * runs this file — so an interpolated class generates no CSS at all and the
 * element renders unstyled. There is no error and no console line; `text-amber`
 * shipped into `icefall-admin` this way and a caution sentence rendered as
 * ordinary grey body text.
 *
 * AND THIS APP IS THE WORST PLACE IN THE FAMILY TO TRY IT, for a reason that
 * makes the refactor look SAFER rather than riskier. Four of these tone names —
 * `azure`, `summit`, `alert`, `danger` — are EXACT token names exported through
 * `@theme`. So `bg-${tone}` expands, in a reviewer's head, to `bg-azure`,
 * `bg-summit`, `bg-alert`, `bg-danger`: four real, valid, currently-used class
 * names. The diff reads as verified on inspection and still generates nothing.
 *
 * (`icefall-admin`'s equivalent uses `green | amber | red`, which merely LOOK
 * like colours — `amber` is not a token there, which is how its bug happened.
 * Names that ARE tokens are the more dangerous case, not the milder one.)
 *
 * It also defeats the one check that finds these. The family's dead-class audit
 * extracts class names from string literals and asks the generated stylesheet
 * whether a rule exists; a class assembled at runtime is invisible to the
 * extractor AND generated by nothing — dead and unreported, which is the worst
 * combination available. Verified 2026-08-29: no app in the family does this.
 * The day one does, the audit silently stops covering it with no signal that its
 * coverage shrank.
 */

/**
 * A statement the reader must not miss. Same left-rule idiom as `Disclaimer`
 * in the athlete app, with a tone, because a lapsed licence and a routine note
 * cannot look identical.
 */
export function Notice({
  children,
  tone = "azure",
  className,
}: {
  children: ReactNode;
  tone?: NoticeTone;
  className?: string;
}) {
  return (
    <div
      className={cn(
        "rounded-r-tile border-l bg-white/[0.02] py-3 pl-3.5 pr-3.5",
        tone === "neutral" && "border-hairline-strong",
        tone === "azure" && "border-azure/40",
        tone === "summit" && "border-summit/50",
        tone === "alert" && "border-alert/50",
        tone === "danger" && "border-danger/55",
        className,
      )}
    >
      <div className="text-[12px] leading-relaxed text-mist">{children}</div>
    </div>
  );
}

export function Field({
  label,
  hint,
  children,
}: {
  label: string;
  hint?: string;
  children: ReactNode;
}) {
  return (
    <label className="block">
      <span className="section-label">{label}</span>
      <div className="mt-2">{children}</div>
      {hint && <p className="mt-1.5 text-[11px] leading-relaxed text-mist-dim">{hint}</p>}
    </label>
  );
}

/** One input treatment, so a form never looks assembled from two apps. */
export const inputClass =
  "w-full rounded-tile border border-hairline bg-elevated/60 px-3 py-2.5 text-[14px] text-snow outline-none transition-colors placeholder:text-mist-dim focus:border-azure";
