-- ICEFALL — CANONICAL CATALOGUE SEED. GENERATED, DO NOT HAND-EDIT.
--
-- Source of truth:
--   mountains  icefall-web/src/data/peaks.ts      (52)
--   treks      icefall-web/src/data/trekRecords.ts (252)
--   companies  icefall-shared/companies.ts
-- Regenerate:  node icefall-supabase/seed/generate.mjs
--
-- WHY GENERATED. Four apps once held four company lists with zero overlap, and
-- two files disagreed about Ama Dablam by two metres. A hand-written seed is a
-- fifth copy that drifts the same way. This file is derived, so the database and
-- the apps cannot disagree without the generator being changed.
--
-- THE MOUNTAINS AND TREKS ARE REAL: real places, published elevations, keyed by
-- the slugs the apps already use, so consumer surfaces join straight on.
-- EVERY COMPANY IS INVENTED. Do not substitute a real operator (decision 2).
--
-- NOTHING IS VERIFIED. Not one company carries verification_status='verified'.
-- Verification means a named person checked documents on a real date, and the
-- schema enforces it: documents_checked_by is a foreign key to a real profile,
-- so a seeded "verified" company would need a forged reviewer. The three
-- companies the shared fixture marked verified are seeded 'pending' instead, and
-- the fixture was corrected to match rather than left to drift.

begin;

/* ========================================================================== */
/* 1. DESTINATIONS — mountains                                                */
/* ========================================================================== */

insert into public.destinations (id, name, kind, range, region, country, elevation_m) values
  ('everest', 'Mount Everest', 'mountain', 'Mahalangur Himal', 'Himalaya & Asia', 'Nepal / China', 8849),
  ('k2', 'K2', 'mountain', 'Karakoram', 'Himalaya & Asia', 'Pakistan / China', 8611),
  ('kangchenjunga', 'Kangchenjunga', 'mountain', 'Kangchenjunga Himal', 'Himalaya & Asia', 'Nepal / India', 8586),
  ('lhotse', 'Lhotse', 'mountain', 'Mahalangur Himal', 'Himalaya & Asia', 'Nepal / China', 8516),
  ('makalu', 'Makalu', 'mountain', 'Mahalangur Himal', 'Himalaya & Asia', 'Nepal / China', 8485),
  ('cho-oyu', 'Cho Oyu', 'mountain', 'Mahalangur Himal', 'Himalaya & Asia', 'Nepal / China', 8188),
  ('dhaulagiri', 'Dhaulagiri I', 'mountain', 'Dhaulagiri Himal', 'Himalaya & Asia', 'Nepal', 8167),
  ('manaslu', 'Manaslu', 'mountain', 'Mansiri Himal', 'Himalaya & Asia', 'Nepal', 8163),
  ('nanga-parbat', 'Nanga Parbat', 'mountain', 'Himalaya', 'Himalaya & Asia', 'Pakistan', 8126),
  ('annapurna', 'Annapurna I', 'mountain', 'Annapurna Himal', 'Himalaya & Asia', 'Nepal', 8091),
  ('gasherbrum-i', 'Gasherbrum I', 'mountain', 'Karakoram', 'Himalaya & Asia', 'Pakistan / China', 8080),
  ('broad-peak', 'Broad Peak', 'mountain', 'Karakoram', 'Himalaya & Asia', 'Pakistan / China', 8051),
  ('gasherbrum-ii', 'Gasherbrum II', 'mountain', 'Karakoram', 'Himalaya & Asia', 'Pakistan / China', 8035),
  ('shishapangma', 'Shishapangma', 'mountain', 'Jugal Himal', 'Himalaya & Asia', 'China', 8027),
  ('muztagh-tower', 'Muztagh Tower', 'mountain', 'Karakoram', 'Himalaya & Asia', 'Pakistan / China', 7276),
  ('lenin-peak', 'Lenin Peak', 'mountain', 'Trans-Alay', 'Himalaya & Asia', 'Kyrgyzstan / Tajikistan', 7134),
  ('baruntse', 'Baruntse', 'mountain', 'Mahalangur Himal', 'Himalaya & Asia', 'Nepal', 7129),
  ('himlung-himal', 'Himlung Himal', 'mountain', 'Peri Himal', 'Himalaya & Asia', 'Nepal', 7126),
  ('khan-tengri', 'Khan Tengri', 'mountain', 'Tian Shan', 'Himalaya & Asia', 'Kazakhstan / Kyrgyzstan', 7010),
  ('ama-dablam', 'Ama Dablam', 'mountain', 'Mahalangur Himal', 'Himalaya & Asia', 'Nepal', 6814),
  ('kailash', 'Mount Kailash', 'mountain', 'Gangdise', 'Himalaya & Asia', 'China', 6638),
  ('mera-peak', 'Mera Peak', 'mountain', 'Mahalangur Himal', 'Himalaya & Asia', 'Nepal', 6476),
  ('island-peak', 'Island Peak', 'mountain', 'Mahalangur Himal', 'Himalaya & Asia', 'Nepal', 6189),
  ('lobuche-east', 'Lobuche East', 'mountain', 'Mahalangur Himal', 'Himalaya & Asia', 'Nepal', 6119),
  ('aconcagua', 'Aconcagua', 'mountain', 'Andes', 'Americas', 'Argentina', 6961),
  ('ojos-del-salado', 'Ojos del Salado', 'mountain', 'Andes', 'Americas', 'Chile / Argentina', 6893),
  ('huascaran', 'Huascarán', 'mountain', 'Cordillera Blanca', 'Americas', 'Peru', 6768),
  ('chimborazo', 'Chimborazo', 'mountain', 'Andes', 'Americas', 'Ecuador', 6263),
  ('denali', 'Denali', 'mountain', 'Alaska Range', 'Americas', 'United States', 6190),
  ('logan', 'Mount Logan', 'mountain', 'Saint Elias Mountains', 'Americas', 'Canada', 5959),
  ('alpamayo', 'Alpamayo', 'mountain', 'Cordillera Blanca', 'Americas', 'Peru', 5947),
  ('cotopaxi', 'Cotopaxi', 'mountain', 'Andes', 'Americas', 'Ecuador', 5897),
  ('rainier', 'Mount Rainier', 'mountain', 'Cascades', 'Americas', 'United States', 4392),
  ('baker', 'Mount Baker', 'mountain', 'Cascades', 'Americas', 'United States', 3286),
  ('elbrus', 'Mount Elbrus', 'mountain', 'Caucasus', 'Europe', 'Russia', 5642),
  ('dykh-tau', 'Dykh-Tau', 'mountain', 'Caucasus', 'Europe', 'Russia', 5205),
  ('ararat', 'Mount Ararat', 'mountain', 'Armenian Highlands', 'Europe', 'Turkey', 5137),
  ('kazbek', 'Mount Kazbek', 'mountain', 'Caucasus', 'Europe', 'Georgia / Russia', 5054),
  ('mont-blanc', 'Mont Blanc', 'mountain', 'Graian Alps', 'Europe', 'France / Italy', 4806),
  ('matterhorn', 'Matterhorn', 'mountain', 'Pennine Alps', 'Europe', 'Switzerland / Italy', 4478),
  ('eiger', 'Eiger', 'mountain', 'Bernese Alps', 'Europe', 'Switzerland', 3967),
  ('grossglockner', 'Grossglockner', 'mountain', 'Hohe Tauern', 'Europe', 'Austria', 3798),
  ('kilimanjaro', 'Mount Kilimanjaro', 'mountain', 'Eastern Rift', 'Africa', 'Tanzania', 5895),
  ('mount-kenya', 'Mount Kenya', 'mountain', 'Eastern Rift', 'Africa', 'Kenya', 5199),
  ('stanley', 'Mount Stanley', 'mountain', 'Rwenzori', 'Africa', 'Uganda / DR Congo', 5109),
  ('speke', 'Mount Speke', 'mountain', 'Rwenzori', 'Africa', 'Uganda', 4890),
  ('toubkal', 'Mount Toubkal', 'mountain', 'High Atlas', 'Africa', 'Morocco', 4167),
  ('vinson', 'Vinson Massif', 'mountain', 'Sentinel Range', 'Oceania & Antarctica', 'Antarctica', 4892),
  ('carstensz', 'Carstensz Pyramid', 'mountain', 'Sudirman Range', 'Oceania & Antarctica', 'Indonesia', 4884),
  ('aoraki', 'Aoraki / Mount Cook', 'mountain', 'Southern Alps', 'Oceania & Antarctica', 'New Zealand', 3724),
  ('fuji', 'Mount Fuji', 'mountain', 'Fuji Volcanic Zone', 'Himalaya & Asia', 'Japan', 3776),
  ('kosciuszko', 'Mount Kosciuszko', 'mountain', 'Snowy Mountains', 'Oceania & Antarctica', 'Australia', 2228)
on conflict (id) do update set
  name = excluded.name, kind = excluded.kind, range = excluded.range,
  region = excluded.region, country = excluded.country, elevation_m = excluded.elevation_m;

/* ========================================================================== */
/* 2. DESTINATIONS — treks                                                    */
/*                                                                            */
/* elevation_m is NULL for every trek, and the schema insists                 */
/* (destinations_trek_has_no_summit). A trek has no summit; the height it     */
/* reaches is max_altitude_m, which is a different claim.                     */
/* ========================================================================== */

insert into public.destinations (id, name, kind, region, country, max_altitude_m, duration_days_min, duration_days_max) values
  ('tour-du-mont-blanc', 'Tour du Mont Blanc', 'trek', 'alps', 'France / Italy / Switzerland', 2665, 10, 11),
  ('walkers-haute-route', 'Walker''s Haute Route', 'trek', 'alps', 'France / Switzerland', 2987, 13, 14),
  ('chamonix-zermatt-haute-route', 'Chamonix–Zermatt Haute Route', 'trek', 'alps', 'France / Switzerland', 3710, 6, 7),
  ('tour-du-matterhorn', 'Tour du Matterhorn', 'trek', 'alps', 'Switzerland / Italy', 3295, 9, 11),
  ('tour-des-combins', 'Tour des Combins', 'trek', 'alps', 'Switzerland / Italy', 2846, 6, 8),
  ('tour-de-la-vanoise', 'Tour de la Vanoise', 'trek', 'alps', 'France', 2796, 10, 11),
  ('tour-du-queyras', 'Tour du Queyras', 'trek', 'alps', 'France', 2884, 8, 10),
  ('via-alpina', 'Via Alpina', 'trek', 'alps', 'Italy / Slovenia / Austria / Germany / Liechtenstein / Switzerland / France / Monaco', 3019, null, null),
  ('stubai-high-trail', 'Stubai High Trail', 'trek', 'alps', 'Austria', 2858, 8, 9),
  ('berlin-high-trail', 'Berlin High Trail', 'trek', 'alps', 'Austria', 3134, 7, 8),
  ('zillertal-alps-high-trail', 'Zillertal Alps High Trail', 'trek', 'alps', 'Austria', 3134, 7, 8),
  ('adlerweg', 'Adlerweg', 'trek', 'alps', 'Austria', 2870, 24, 33),
  ('e5-alpine-crossing', 'E5 Alpine Crossing', 'trek', 'alps', 'Germany / Austria / Italy', 2995, 6, 8),
  ('gran-paradiso-trek', 'Gran Paradiso Trek', 'trek', 'alps', 'Italy', 3296, 12, 14),
  ('tour-of-the-bernina', 'Tour of the Bernina', 'trek', 'alps', 'Switzerland / Italy', null, 8, 9),
  ('chimborazo-circuit', 'Chimborazo Circuit', 'trek', 'andes-north', 'Ecuador', 4800, 4, 5),
  ('choro-trek', 'Choro Trek', 'trek', 'andes-north', 'Bolivia', 4859, 3, 4),
  ('condor-trek', 'Condor Trek', 'trek', 'andes-north', 'Ecuador', 4500, 4, 5),
  ('condoriri-trek', 'Condoriri Trek', 'trek', 'andes-north', 'Bolivia', 5100, 3, 5),
  ('cordillera-apolobamba-trek', 'Cordillera Apolobamba Trek', 'trek', 'andes-north', 'Bolivia', 5100, 6, 8),
  ('cordillera-real-trek', 'Cordillera Real Trek', 'trek', 'andes-north', 'Bolivia', 5100, 12, 12),
  ('cotopaxi-base-camp-and-refuge-trek', 'Cotopaxi Base Camp and Refuge Trek', 'trek', 'andes-north', 'Ecuador', 4864, 2, 2),
  ('el-altar-trek', 'El Altar Trek', 'trek', 'andes-north', 'Ecuador', 4300, 3, 4),
  ('illampu-circuit', 'Illampu Circuit', 'trek', 'andes-north', 'Bolivia', 5045, 6, 7),
  ('ingapirca-inca-trail', 'Ingapirca Inca Trail', 'trek', 'andes-north', 'Ecuador', 4400, 3, 3),
  ('quilotoa-loop', 'Quilotoa Loop', 'trek', 'andes-north', 'Ecuador', 3914, 3, 4),
  ('quilotoa-chimborazo-trek', 'Quilotoa–Chimborazo Trek', 'trek', 'andes-north', 'Ecuador', 5000, 8, 14),
  ('sajama-circuit', 'Sajama Circuit', 'trek', 'andes-north', 'Bolivia', 4900, 4, 5),
  ('takesi-trek', 'Takesi Trek', 'trek', 'andes-north', 'Bolivia', 4700, 2, 3),
  ('yunga-cruz-trek', 'Yunga Cruz Trek', 'trek', 'andes-north', 'Bolivia', 4700, 3, 4),
  ('annapurna-circuit-trek', 'Annapurna Circuit Trek', 'trek', 'annapurna', 'Nepal', 5416, 12, 20),
  ('annapurna-circuit-tilicho-lake', 'Annapurna Circuit + Tilicho Lake', 'trek', 'annapurna', 'Nepal', 5416, 15, 20),
  ('annapurna-base-camp-trek', 'Annapurna Base Camp Trek', 'trek', 'annapurna', 'Nepal', 4130, 7, 12),
  ('annapurna-sanctuary-trek', 'Annapurna Sanctuary Trek', 'trek', 'annapurna', 'Nepal', 4130, 9, 14),
  ('mardi-himal-trek', 'Mardi Himal Trek', 'trek', 'annapurna', 'Nepal', 4500, 5, 7),
  ('ghorepani-poon-hill-trek', 'Ghorepani–Poon Hill Trek', 'trek', 'annapurna', 'Nepal', 3210, 4, 5),
  ('khopra-ridge-trek', 'Khopra Ridge Trek', 'trek', 'annapurna', 'Nepal', 3660, 6, 9),
  ('nar-phu-valley-trek', 'Nar Phu Valley Trek', 'trek', 'annapurna', 'Nepal', 5320, 10, 15),
  ('tilicho-lake-trek', 'Tilicho Lake Trek', 'trek', 'annapurna', 'Nepal', 4919, 7, 14),
  ('jomsom-muktinath-trek', 'Jomsom–Muktinath Trek', 'trek', 'annapurna', 'Nepal', 3762, 5, 10),
  ('mount-toubkal-circuit-trek', 'Mount Toubkal Circuit Trek', 'trek', 'atlas', 'Morocco', 4167, 6, 8),
  ('high-atlas-trek', 'High Atlas Trek', 'trek', 'atlas', 'Morocco', null, null, null),
  ('mgoun-massif-trek', 'M''Goun Massif Trek', 'trek', 'atlas', 'Morocco', 4071, 5, 7),
  ('jebel-saghro-trek', 'Jebel Saghro Trek', 'trek', 'atlas', 'Morocco', 2592, 6, 8),
  ('australian-alps-walking-track', 'Australian Alps Walking Track', 'trek', 'australia', 'Australia', 2228, 30, 60),
  ('bibbulmun-track', 'Bibbulmun Track', 'trek', 'australia', 'Australia', 582, 42, 56),
  ('cape-to-cape-track', 'Cape to Cape Track', 'trek', 'australia', 'Australia', null, 5, 8),
  ('great-ocean-walk', 'Great Ocean Walk', 'trek', 'australia', 'Australia', null, 7, 8),
  ('heysen-trail', 'Heysen Trail', 'trek', 'australia', 'Australia', null, 50, 60),
  ('larapinta-trail', 'Larapinta Trail', 'trek', 'australia', 'Australia', 1380, 15, 17),
  ('main-range-track', 'Main Range Track', 'trek', 'australia', 'Australia', 2228, 1, 1),
  ('overland-track', 'Overland Track', 'trek', 'australia', 'Australia', 1250, 6, 6),
  ('six-foot-track', 'Six Foot Track', 'trek', 'australia', 'Australia', null, 3, 3),
  ('south-coast-track', 'South Coast Track', 'trek', 'australia', 'Australia', 900, 6, 8),
  ('thorsborne-trail', 'Thorsborne Trail', 'trek', 'australia', 'Australia', null, 3, 4),
  ('three-capes-track', 'Three Capes Track', 'trek', 'australia', 'Australia', 490, 4, 4),
  ('bumdra-trek', 'Bumdra Trek', 'trek', 'bhutan', 'Bhutan', 3800, 2, 2),
  ('bumthang-owl-trek', 'Bumthang Owl Trek', 'trek', 'bhutan', 'Bhutan', 3870, 3, 3),
  ('dagala-thousand-lakes-trek', 'Dagala Thousand Lakes Trek', 'trek', 'bhutan', 'Bhutan', null, 5, 6),
  ('druk-path-trek', 'Druk Path Trek', 'trek', 'bhutan', 'Bhutan', 4210, 5, 6),
  ('jomolhari-trek', 'Jomolhari Trek', 'trek', 'bhutan', 'Bhutan', 4930, 6, 9),
  ('laya-gasa-trek', 'Laya–Gasa Trek', 'trek', 'bhutan', 'Bhutan', 5005, 10, 14),
  ('merak-sakteng-trek', 'Merak–Sakteng Trek', 'trek', 'bhutan', 'Bhutan', 4153, 7, 9),
  ('nabji-korphu-trail', 'Nabji Korphu Trail', 'trek', 'bhutan', 'Bhutan', 1636, 3, 4),
  ('snowman-trek', 'Snowman Trek', 'trek', 'bhutan', 'Bhutan', 5320, 25, 30),
  ('trans-bhutan-trail', 'Trans Bhutan Trail', 'trek', 'bhutan', 'Bhutan', null, 25, 36),
  ('ala-archa-trek', 'Ala Archa Trek', 'trek', 'central-asia', 'Kyrgyzstan', 3400, 1, 2),
  ('ala-kul-trek', 'Ala-Kul Trek', 'trek', 'central-asia', 'Kyrgyzstan', 3860, 3, 4),
  ('arslanbob-walnut-forest-trek', 'Arslanbob Walnut Forest Trek', 'trek', 'central-asia', 'Kyrgyzstan', 2200, 2, 3),
  ('bartang-valley-trek', 'Bartang Valley Trek', 'trek', 'central-asia', 'Tajikistan', 4600, 7, 10),
  ('fann-mountains-trek', 'Fann Mountains Trek', 'trek', 'central-asia', 'Tajikistan', 3780, 4, 4),
  ('heights-of-alay-trek', 'Heights of Alay Trek', 'trek', 'central-asia', 'Kyrgyzstan', 4200, 7, 9),
  ('jyrgalan-boz-uchuk-lakes-trek', 'Jyrgalan Boz Uchuk Lakes Trek', 'trek', 'central-asia', 'Kyrgyzstan', 3400, 3, 4),
  ('keskenkija-loop', 'Keskenkija Loop', 'trek', 'central-asia', 'Kyrgyzstan', 3300, 3, 3),
  ('kol-suu-lake-trek', 'Kol Suu Lake Trek', 'trek', 'central-asia', 'Kyrgyzstan', 3500, 3, 4),
  ('pamir-trek', 'Pamir Trek', 'trek', 'central-asia', 'Tajikistan', 5010, null, null),
  ('peak-lenin-base-camp-trek', 'Peak Lenin Base Camp Trek', 'trek', 'central-asia', 'Kyrgyzstan', 4400, 4, 6),
  ('seven-lakes-trek', 'Seven Lakes Trek', 'trek', 'central-asia', 'Tajikistan', 2400, 1, 2),
  ('song-kul-trek', 'Song-Kul Trek', 'trek', 'central-asia', 'Kyrgyzstan', null, 2, 4),
  ('tien-shan-trek', 'Tien Shan Trek', 'trek', 'central-asia', 'Kyrgyzstan', 4000, 10, 10),
  ('huayhuash-circuit-trek', 'Huayhuash Circuit Trek', 'trek', 'cordillera', 'Peru', 5000, 8, 12),
  ('santa-cruz-trek', 'Santa Cruz Trek', 'trek', 'cordillera', 'Peru', 4750, 3, 4),
  ('alpamayo-circuit-trek', 'Alpamayo Circuit Trek', 'trek', 'cordillera', 'Peru', 4850, 10, 12),
  ('cedros-alpamayo-traverse', 'Cedros–Alpamayo Traverse', 'trek', 'cordillera', 'Peru', 4860, 8, 10),
  ('colca-canyon-trek', 'Colca Canyon Trek', 'trek', 'cordillera', 'Peru', 3287, 2, 3),
  ('cotahuasi-canyon-trek', 'Cotahuasi Canyon Trek', 'trek', 'cordillera', 'Peru', null, 3, 5),
  ('inca-trail-to-machu-picchu', 'Inca Trail to Machu Picchu', 'trek', 'cusco', 'Peru', 4215, 4, 4),
  ('short-inca-trail', 'Short Inca Trail', 'trek', 'cusco', 'Peru', 2720, 2, 2),
  ('salkantay-trek', 'Salkantay Trek', 'trek', 'cusco', 'Peru', 4630, 4, 5),
  ('salkantay-inca-trail-trek', 'Salkantay–Inca Trail Trek', 'trek', 'cusco', 'Peru', 5100, 7, 7),
  ('lares-trek', 'Lares Trek', 'trek', 'cusco', 'Peru', 4450, 3, 4),
  ('choquequirao-trek', 'Choquequirao Trek', 'trek', 'cusco', 'Peru', 3050, 4, 5),
  ('choquequirao-machu-picchu-trek', 'Choquequirao–Machu Picchu Trek', 'trek', 'cusco', 'Peru', 4668, 8, 9),
  ('ausangate-trek', 'Ausangate Trek', 'trek', 'cusco', 'Peru', 5165, 4, 6),
  ('ausangate-rainbow-mountain-trek', 'Ausangate & Rainbow Mountain Trek', 'trek', 'cusco', 'Peru', 5165, 6, 7),
  ('huchuy-qosqo-trek', 'Huchuy Qosqo Trek', 'trek', 'cusco', 'Peru', 4200, 2, 3),
  ('ancascocha-trek', 'Ancascocha Trek', 'trek', 'cusco', 'Peru', 4650, 4, 5),
  ('vilcabamba-to-machu-picchu', 'Vilcabamba to Machu Picchu', 'trek', 'cusco', 'Peru', 4600, 5, 7),
  ('dolomites-alta-via-1', 'Dolomites Alta Via 1', 'trek', 'dolomites', 'Italy', 2752, 7, 12),
  ('dolomites-alta-via-2', 'Dolomites Alta Via 2', 'trek', 'dolomites', 'Italy', 2885, 12, 15),
  ('dolomites-alta-via-3', 'Dolomites Alta Via 3', 'trek', 'dolomites', 'Italy', 2378, 8, 10),
  ('dolomites-alta-via-4', 'Dolomites Alta Via 4', 'trek', 'dolomites', 'Italy', 2624, 6, 6),
  ('dolomites-alta-via-5', 'Dolomites Alta Via 5', 'trek', 'dolomites', 'Italy', 2644, 6, 7),
  ('dolomites-alta-via-6', 'Dolomites Alta Via 6', 'trek', 'dolomites', 'Italy', 2450, 10, 11),
  ('cathedral-peak-circuit', 'Cathedral Peak Circuit', 'trek', 'drakensberg', 'South Africa', null, 2, 3),
  ('drakensberg-amphitheatre-trek', 'Drakensberg Amphitheatre Trek', 'trek', 'drakensberg', 'South Africa', 3000, 1, 2),
  ('drakensberg-grand-traverse', 'Drakensberg Grand Traverse', 'trek', 'drakensberg', 'South Africa / Lesotho', 3482, 10, 14),
  ('giants-cup-trail', 'Giant''s Cup Trail', 'trek', 'drakensberg', 'South Africa', null, 5, 5),
  ('injisuthi-to-cathedral-peak-traverse', 'Injisuthi to Cathedral Peak Traverse', 'trek', 'drakensberg', 'South Africa / Lesotho', null, 5, 6),
  ('mnweni-circuit', 'Mnweni Circuit', 'trek', 'drakensberg', 'South Africa / Lesotho', null, 3, 4),
  ('rhino-peak-hike', 'Rhino Peak Hike', 'trek', 'drakensberg', 'South Africa', 3051, 1, 2),
  ('sani-pass-to-thabana-ntlenyana', 'Sani Pass to Thabana Ntlenyana', 'trek', 'drakensberg', 'South Africa / Lesotho', 3482, 2, 3),
  ('kilimanjaro-machame-route', 'Kilimanjaro Machame Route', 'trek', 'east-africa', 'Tanzania', 5895, 6, 7),
  ('kilimanjaro-lemosho-route', 'Kilimanjaro Lemosho Route', 'trek', 'east-africa', 'Tanzania', 5895, 7, 8),
  ('kilimanjaro-rongai-route', 'Kilimanjaro Rongai Route', 'trek', 'east-africa', 'Tanzania', 5895, 6, 7),
  ('kilimanjaro-northern-circuit', 'Kilimanjaro Northern Circuit', 'trek', 'east-africa', 'Tanzania', 5895, 8, 9),
  ('kilimanjaro-marangu-route', 'Kilimanjaro Marangu Route', 'trek', 'east-africa', 'Tanzania', 5895, 5, 6),
  ('mount-meru-trek', 'Mount Meru Trek', 'trek', 'east-africa', 'Tanzania', 4562, 3, 4),
  ('mount-kenya-sirimon-route', 'Mount Kenya Sirimon Route', 'trek', 'east-africa', 'Kenya', 4985, 4, 5),
  ('mount-kenya-chogoria-route', 'Mount Kenya Chogoria Route', 'trek', 'east-africa', 'Kenya', 4985, 4, 6),
  ('mount-kenya-naro-moru-route', 'Mount Kenya Naro Moru Route', 'trek', 'east-africa', 'Kenya', 4985, 3, 4),
  ('rwenzori-central-circuit', 'Rwenzori Central Circuit', 'trek', 'east-africa', 'Uganda', 4372, 7, 9),
  ('rwenzori-kilembe-trail', 'Rwenzori Kilembe Trail', 'trek', 'east-africa', 'Uganda', 4450, 7, 8),
  ('simien-mountains-trek', 'Simien Mountains Trek', 'trek', 'east-africa', 'Ethiopia', 4550, 4, 10),
  ('bale-mountains-trek', 'Bale Mountains Trek', 'trek', 'east-africa', 'Ethiopia', 4377, 6, 9),
  ('camino-franc-s', 'Camino Francés', 'trek', 'iberia', 'France / Spain', 1505, 30, 35),
  ('camino-portugu-s', 'Camino Portugués', 'trek', 'iberia', 'Portugal / Spain', 405, 12, 14),
  ('camino-portugu-s-coastal', 'Camino Portugués Coastal', 'trek', 'iberia', 'Portugal / Spain', null, 12, 15),
  ('camino-del-norte', 'Camino del Norte', 'trek', 'iberia', 'Spain', 708, 32, 40),
  ('camino-primitivo', 'Camino Primitivo', 'trek', 'iberia', 'Spain', 1200, 14, 16),
  ('camino-ingl-s', 'Camino Inglés', 'trek', 'iberia', 'Spain', 454, 5, 6),
  ('via-de-la-plata', 'Via de la Plata', 'trek', 'iberia', 'Spain', 1360, 42, 56),
  ('camino-finisterre', 'Camino Finisterre', 'trek', 'iberia', 'Spain', 556, 4, 6),
  ('gr20-corsica-trek', 'GR20 Corsica Trek', 'trek', 'iberia', 'France', 2607, 15, 16),
  ('gr10-pyrenees', 'GR10 Pyrenees', 'trek', 'iberia', 'France', 2734, 50, 60),
  ('gr11-pyrenees', 'GR11 Pyrenees', 'trek', 'iberia', 'Spain', 2800, 42, 50),
  ('amalfi-coast-path-of-the-gods', 'Amalfi Coast / Path of the Gods', 'trek', 'iberia', 'Italy', 650, 1, 1),
  ('via-francigena', 'Via Francigena', 'trek', 'iberia', 'United Kingdom / France / Switzerland / Italy', 2473, 90, 100),
  ('mallorca-gr221', 'Mallorca GR221', 'trek', 'iberia', 'Spain', 1205, 8, 10),
  ('la-gomera-gr132', 'La Gomera GR132', 'trek', 'iberia', 'Spain', 879, 6, 8),
  ('laugavegur-trail', 'Laugavegur Trail', 'trek', 'iceland', 'Iceland', 1050, 3, 4),
  ('fimmv-r-uh-ls-trek', 'Fimmvörðuháls Trek', 'trek', 'iceland', 'Iceland', 1045, 1, 2),
  ('laugavegur-fimmv-r-uh-ls-trek', 'Laugavegur & Fimmvörðuháls Trek', 'trek', 'iceland', 'Iceland', 1050, 5, 6),
  ('hornstrandir-trek', 'Hornstrandir Trek', 'trek', 'iceland', 'Iceland', null, 3, 7),
  ('kjalvegur-trail', 'Kjalvegur Trail', 'trek', 'iceland', 'Iceland', 778, 2, 3),
  ('daisetsuzan-grand-traverse', 'Daisetsuzan Grand Traverse', 'trek', 'japan', 'Japan', 2291, 5, 7),
  ('hakuba-three-peaks-traverse', 'Hakuba Three Peaks Traverse', 'trek', 'japan', 'Japan', 2932, 2, 3),
  ('kumano-kodo', 'Kumano Kodo', 'trek', 'japan', 'Japan', null, 4, 6),
  ('kumano-kodo-kohechi', 'Kumano Kodo Kohechi', 'trek', 'japan', 'Japan', 1220, 4, 4),
  ('michinoku-coastal-trail', 'Michinoku Coastal Trail', 'trek', 'japan', 'Japan', null, 45, 60),
  ('mount-fuji-climbing-routes', 'Mount Fuji Climbing Routes', 'trek', 'japan', 'Japan', 3776, 1, 2),
  ('mount-ontake-pilgrim-route', 'Mount Ontake Pilgrim Route', 'trek', 'japan', 'Japan', 3067, 2, 2),
  ('nakasendo-trail', 'Nakasendo Trail', 'trek', 'japan', 'Japan', 1531, null, null),
  ('northern-alps-trekking-circuit', 'Northern Alps Trekking Circuit', 'trek', 'japan', 'Japan', 3190, null, null),
  ('shikoku-pilgrimage', 'Shikoku Pilgrimage', 'trek', 'japan', 'Japan', 912, 30, 60),
  ('tateyama-kurobe-alpine-trek', 'Tateyama–Kurobe Alpine Trek', 'trek', 'japan', 'Japan', 3015, null, null),
  ('yakushima-miyanoura-dake', 'Yakushima Miyanoura-dake', 'trek', 'japan', 'Japan', 1936, 2, 2),
  ('everest-base-camp-trek', 'Everest Base Camp Trek', 'trek', 'khumbu', 'Nepal', 5545, 12, 14),
  ('everest-base-camp-via-gokyo-lakes', 'Everest Base Camp via Gokyo Lakes', 'trek', 'khumbu', 'Nepal', 5545, 16, 18),
  ('everest-three-passes-trek', 'Everest Three Passes Trek', 'trek', 'khumbu', 'Nepal', 5545, 18, 21),
  ('gokyo-lakes-trek', 'Gokyo Lakes Trek', 'trek', 'khumbu', 'Nepal', 5357, 12, 14),
  ('gokyo-renjo-la-trek', 'Gokyo–Renjo La Trek', 'trek', 'khumbu', 'Nepal', 5360, 13, 15),
  ('cho-la-pass-trek', 'Cho La Pass Trek', 'trek', 'khumbu', 'Nepal', 5545, 15, 18),
  ('everest-view-trek', 'Everest View Trek', 'trek', 'khumbu', 'Nepal', 3880, 5, 7),
  ('ama-dablam-base-camp-trek', 'Ama Dablam Base Camp Trek', 'trek', 'khumbu', 'Nepal', 4570, 8, 11),
  ('everest-high-passes-island-peak-trek', 'Everest High Passes & Island Peak Trek', 'trek', 'khumbu', 'Nepal', 6189, 21, 23),
  ('jiri-to-everest-base-camp-trek', 'Jiri to Everest Base Camp Trek', 'trek', 'khumbu', 'Nepal', 5545, 18, 24),
  ('langtang-valley-trek', 'Langtang Valley Trek', 'trek', 'langtang', 'Nepal', 4773, 7, 9),
  ('langtang-gosaikunda-trek', 'Langtang–Gosaikunda Trek', 'trek', 'langtang', 'Nepal', 4610, 12, 15),
  ('gosaikunda-trek', 'Gosaikunda Trek', 'trek', 'langtang', 'Nepal', 4380, 5, 7),
  ('helambu-trek', 'Helambu Trek', 'trek', 'langtang', 'Nepal', 3650, 5, 7),
  ('tamang-heritage-trail', 'Tamang Heritage Trail', 'trek', 'langtang', 'Nepal', 3165, 6, 8),
  ('manaslu-circuit-trek', 'Manaslu Circuit Trek', 'trek', 'nepal-remote', 'Nepal', 5106, 13, 16),
  ('tsum-valley-trek', 'Tsum Valley Trek', 'trek', 'nepal-remote', 'Nepal', 3700, 11, 18),
  ('upper-mustang-trek', 'Upper Mustang Trek', 'trek', 'nepal-remote', 'Nepal', 4230, 10, 16),
  ('upper-dolpo-trek', 'Upper Dolpo Trek', 'trek', 'nepal-remote', 'Nepal', null, 21, 27),
  ('lower-dolpo-trek', 'Lower Dolpo Trek', 'trek', 'nepal-remote', 'Nepal', 5190, 15, 20),
  ('kanchenjunga-base-camp-trek', 'Kanchenjunga Base Camp Trek', 'trek', 'nepal-remote', 'Nepal', 5143, 20, 24),
  ('makalu-base-camp-trek', 'Makalu Base Camp Trek', 'trek', 'nepal-remote', 'Nepal', 4870, 18, 22),
  ('dhaulagiri-circuit-trek', 'Dhaulagiri Circuit Trek', 'trek', 'nepal-remote', 'Nepal', 5360, 17, 21),
  ('nar-phu-annapurna-circuit', 'Nar Phu + Annapurna Circuit', 'trek', 'nepal-remote', 'Nepal', 5416, 17, 21),
  ('ruby-valley-trek', 'Ruby Valley Trek', 'trek', 'nepal-remote', 'Nepal', 3842, 7, 12),
  ('rara-lake-trek', 'Rara Lake Trek', 'trek', 'nepal-remote', 'Nepal', 3691, 10, 15),
  ('abel-tasman-coast-track', 'Abel Tasman Coast Track', 'trek', 'new-zealand', 'New Zealand', 200, 3, 5),
  ('copland-track', 'Copland Track', 'trek', 'new-zealand', 'New Zealand', null, 2, 3),
  ('gillespie-pass-circuit', 'Gillespie Pass Circuit', 'trek', 'new-zealand', 'New Zealand', 1500, 3, 3),
  ('heaphy-track', 'Heaphy Track', 'trek', 'new-zealand', 'New Zealand', 915, 4, 6),
  ('hump-ridge-track', 'Hump Ridge Track', 'trek', 'new-zealand', 'New Zealand', null, 3, 3),
  ('kepler-track', 'Kepler Track', 'trek', 'new-zealand', 'New Zealand', 1472, 3, 4),
  ('milford-track', 'Milford Track', 'trek', 'new-zealand', 'New Zealand', 1154, 4, 4),
  ('mueller-hut-route', 'Mueller Hut Route', 'trek', 'new-zealand', 'New Zealand', 1800, 1, 2),
  ('paparoa-track', 'Paparoa Track', 'trek', 'new-zealand', 'New Zealand', null, 3, 3),
  ('rakiura-track', 'Rakiura Track', 'trek', 'new-zealand', 'New Zealand', null, 3, 3),
  ('rees-dart-track', 'Rees-Dart Track', 'trek', 'new-zealand', 'New Zealand', 1447, 4, 5),
  ('routeburn-track', 'Routeburn Track', 'trek', 'new-zealand', 'New Zealand', 1255, 2, 4),
  ('stewart-island-north-west-circuit', 'Stewart Island North-West Circuit', 'trek', 'new-zealand', 'New Zealand', null, 8, 10),
  ('te-araroa', 'Te Araroa', 'trek', 'new-zealand', 'New Zealand', 1925, 120, 180),
  ('tongariro-alpine-crossing', 'Tongariro Alpine Crossing', 'trek', 'new-zealand', 'New Zealand', 1886, 1, 1),
  ('tongariro-northern-circuit', 'Tongariro Northern Circuit', 'trek', 'new-zealand', 'New Zealand', 1886, 3, 4),
  ('travers-sabine-circuit', 'Travers–Sabine Circuit', 'trek', 'new-zealand', 'New Zealand', 1787, 5, 6),
  ('appalachian-trail', 'Appalachian Trail', 'trek', 'north-america', 'United States', 2025, 150, 210),
  ('arizona-trail', 'Arizona Trail', 'trek', 'north-america', 'United States', null, null, null),
  ('berg-lake-trail', 'Berg Lake Trail', 'trek', 'north-america', 'Canada', 1646, 2, 3),
  ('chilkoot-trail', 'Chilkoot Trail', 'trek', 'north-america', 'United States', 1067, 3, 5),
  ('colorado-trail', 'Colorado Trail', 'trek', 'north-america', 'United States', 4045, 28, 42),
  ('continental-divide-trail', 'Continental Divide Trail', 'trek', 'north-america', 'United States', 4350, 150, 200),
  ('grand-canyon-rim-to-rim', 'Grand Canyon Rim-to-Rim', 'trek', 'north-america', 'United States', 2512, 1, 3),
  ('high-sierra-trail', 'High Sierra Trail', 'trek', 'north-america', 'United States', 4421, 6, 10),
  ('john-muir-trail', 'John Muir Trail', 'trek', 'north-america', 'United States', 4421, 18, 24),
  ('juan-de-fuca-trail', 'Juan de Fuca Trail', 'trek', 'north-america', 'Canada', null, 4, 6),
  ('mount-baker-chain-lakes-loop', 'Mount Baker Chain Lakes Loop', 'trek', 'north-america', 'United States', 1650, 1, 2),
  ('pacific-crest-trail', 'Pacific Crest Trail', 'trek', 'north-america', 'United States', 4009, 120, 180),
  ('rae-lakes-loop', 'Rae Lakes Loop', 'trek', 'north-america', 'United States', 3650, 4, 5),
  ('rockwall-trail', 'Rockwall Trail', 'trek', 'north-america', 'Canada', null, null, null),
  ('skyline-trail-jasper', 'Skyline Trail Jasper', 'trek', 'north-america', 'Canada', 2511, 2, 3),
  ('teton-crest-trail', 'Teton Crest Trail', 'trek', 'north-america', 'United States', 3290, 4, 5),
  ('the-long-trail', 'The Long Trail', 'trek', 'north-america', 'United States', 1339, 20, 30),
  ('west-coast-trail', 'West Coast Trail', 'trek', 'north-america', 'Canada', null, 6, 8),
  ('wonderland-trail', 'Wonderland Trail', 'trek', 'north-america', 'United States', 2060, 10, 14),
  ('yosemite-high-country-trek', 'Yosemite High Country Trek', 'trek', 'north-america', 'United States', null, null, null),
  ('zion-traverse', 'Zion Traverse', 'trek', 'north-america', 'United States', null, null, null),
  ('torres-del-paine-w-trek', 'Torres del Paine W Trek', 'trek', 'patagonia', 'Chile', 870, 4, 5),
  ('torres-del-paine-o-circuit', 'Torres del Paine O Circuit', 'trek', 'patagonia', 'Chile', 1200, 7, 9),
  ('torres-del-paine-q-circuit', 'Torres del Paine Q Circuit', 'trek', 'patagonia', 'Chile', 1200, 8, 10),
  ('dientes-de-navarino-trek', 'Dientes de Navarino Trek', 'trek', 'patagonia', 'Chile', 850, 4, 6),
  ('huemul-circuit-trek', 'Huemul Circuit Trek', 'trek', 'patagonia', 'Argentina', 1450, 4, 4),
  ('ohiggins-glacier-trek', 'O''Higgins Glacier Trek', 'trek', 'patagonia', 'Chile', null, 4, 4),
  ('cerro-castillo-circuit', 'Cerro Castillo Circuit', 'trek', 'patagonia', 'Chile', 1300, 4, 4),
  ('cochamo-valley-trek', 'Cochamo Valley Trek', 'trek', 'patagonia', 'Chile', null, 3, 4),
  ('villa-ohiggins-el-chalten-trek', 'Villa O''Higgins–El Chalten Trek', 'trek', 'patagonia', 'Chile / Argentina', null, 1, 2),
  ('fitz-roy-el-chalten-trek', 'Fitz Roy / El Chalten Trek', 'trek', 'patagonia', 'Argentina', 1150, 2, 3),
  ('laguna-de-los-tres-trek', 'Laguna de los Tres Trek', 'trek', 'patagonia', 'Argentina', 1150, 1, 1),
  ('patagonia-ohiggins-trek', 'Patagonia O''Higgins Trek', 'trek', 'patagonia', 'Chile', null, null, null),
  ('beara-way', 'Beara Way', 'trek', 'uk-ireland', 'Ireland', null, 9, 9),
  ('cape-wrath-trail', 'Cape Wrath Trail', 'trek', 'uk-ireland', 'United Kingdom', null, 16, 21),
  ('coast-to-coast-walk', 'Coast-to-Coast Walk', 'trek', 'uk-ireland', 'United Kingdom', 780, 12, 15),
  ('cotswold-way', 'Cotswold Way', 'trek', 'uk-ireland', 'United Kingdom', 330, 7, 10),
  ('cumbria-way', 'Cumbria Way', 'trek', 'uk-ireland', 'United Kingdom', 658, 5, 6),
  ('dales-way', 'Dales Way', 'trek', 'uk-ireland', 'United Kingdom', 520, 6, 8),
  ('dingle-way', 'Dingle Way', 'trek', 'uk-ireland', 'Ireland', 640, 7, 8),
  ('great-glen-way', 'Great Glen Way', 'trek', 'uk-ireland', 'United Kingdom', 375, 5, 7),
  ('hadrians-wall-path', 'Hadrian''s Wall Path', 'trek', 'uk-ireland', 'United Kingdom', 345, 6, 8),
  ('kerry-way', 'Kerry Way', 'trek', 'uk-ireland', 'Ireland', 385, 9, 9),
  ('offas-dyke-path', 'Offa''s Dyke Path', 'trek', 'uk-ireland', 'United Kingdom', 703, 12, 14),
  ('pembrokeshire-coast-path', 'Pembrokeshire Coast Path', 'trek', 'uk-ireland', 'United Kingdom', 175, 12, 15),
  ('pennine-way', 'Pennine Way', 'trek', 'uk-ireland', 'United Kingdom', 893, 16, 19),
  ('skye-trail', 'Skye Trail', 'trek', 'uk-ireland', 'United Kingdom', 719, 7, 7),
  ('south-west-coast-path', 'South West Coast Path', 'trek', 'uk-ireland', 'United Kingdom', 318, 30, 60),
  ('southern-upland-way', 'Southern Upland Way', 'trek', 'uk-ireland', 'United Kingdom', 725, 12, 16),
  ('the-ridgeway', 'The Ridgeway', 'trek', 'uk-ireland', 'United Kingdom', null, 5, 6),
  ('west-highland-way', 'West Highland Way', 'trek', 'uk-ireland', 'United Kingdom', 550, 7, 8),
  ('wicklow-way', 'Wicklow Way', 'trek', 'uk-ireland', 'Ireland', 630, 5, 7)
on conflict (id) do update set
  name = excluded.name, kind = excluded.kind, region = excluded.region,
  country = excluded.country, max_altitude_m = excluded.max_altitude_m,
  duration_days_min = excluded.duration_days_min, duration_days_max = excluded.duration_days_max;

/* ========================================================================== */
/* 3. TREK -> MOUNTAIN LINKS                                                  */
/*                                                                            */
/* 51 links. 0 referenced a mountain that is not in the catalogue and    */
/* are OMITTED rather than invented: none   */
/* A dangling link would fail the foreign key anyway; naming them here is the  */
/* difference between a known gap and a silent one.                           */
/* ========================================================================== */

insert into public.trek_mountains (trek_id, destination_id) values
  ('tour-du-mont-blanc', 'mont-blanc'),
  ('walkers-haute-route', 'mont-blanc'),
  ('walkers-haute-route', 'matterhorn'),
  ('chamonix-zermatt-haute-route', 'mont-blanc'),
  ('chamonix-zermatt-haute-route', 'matterhorn'),
  ('tour-du-matterhorn', 'matterhorn'),
  ('chimborazo-circuit', 'chimborazo'),
  ('cotopaxi-base-camp-and-refuge-trek', 'cotopaxi'),
  ('quilotoa-chimborazo-trek', 'chimborazo'),
  ('annapurna-circuit-trek', 'annapurna'),
  ('annapurna-circuit-tilicho-lake', 'annapurna'),
  ('annapurna-base-camp-trek', 'annapurna'),
  ('annapurna-sanctuary-trek', 'annapurna'),
  ('mount-toubkal-circuit-trek', 'toubkal'),
  ('australian-alps-walking-track', 'kosciuszko'),
  ('main-range-track', 'kosciuszko'),
  ('peak-lenin-base-camp-trek', 'lenin-peak'),
  ('tien-shan-trek', 'khan-tengri'),
  ('alpamayo-circuit-trek', 'alpamayo'),
  ('cedros-alpamayo-traverse', 'alpamayo'),
  ('kilimanjaro-machame-route', 'kilimanjaro'),
  ('kilimanjaro-lemosho-route', 'kilimanjaro'),
  ('kilimanjaro-rongai-route', 'kilimanjaro'),
  ('kilimanjaro-northern-circuit', 'kilimanjaro'),
  ('kilimanjaro-marangu-route', 'kilimanjaro'),
  ('mount-kenya-sirimon-route', 'mount-kenya'),
  ('mount-kenya-chogoria-route', 'mount-kenya'),
  ('mount-kenya-naro-moru-route', 'mount-kenya'),
  ('rwenzori-central-circuit', 'stanley'),
  ('rwenzori-central-circuit', 'speke'),
  ('rwenzori-kilembe-trail', 'stanley'),
  ('mount-fuji-climbing-routes', 'fuji'),
  ('everest-base-camp-trek', 'everest'),
  ('everest-base-camp-via-gokyo-lakes', 'everest'),
  ('everest-three-passes-trek', 'everest'),
  ('everest-three-passes-trek', 'lobuche-east'),
  ('cho-la-pass-trek', 'everest'),
  ('ama-dablam-base-camp-trek', 'ama-dablam'),
  ('everest-high-passes-island-peak-trek', 'everest'),
  ('everest-high-passes-island-peak-trek', 'island-peak'),
  ('everest-high-passes-island-peak-trek', 'lobuche-east'),
  ('jiri-to-everest-base-camp-trek', 'everest'),
  ('manaslu-circuit-trek', 'manaslu'),
  ('kanchenjunga-base-camp-trek', 'kangchenjunga'),
  ('makalu-base-camp-trek', 'makalu'),
  ('dhaulagiri-circuit-trek', 'dhaulagiri'),
  ('nar-phu-annapurna-circuit', 'annapurna'),
  ('copland-track', 'aoraki'),
  ('mueller-hut-route', 'aoraki'),
  ('mount-baker-chain-lakes-loop', 'baker'),
  ('wonderland-trail', 'rainier')
on conflict do nothing;

commit;
