import { supabase } from "@/backend/client";
import type { SupportTicketType } from "@/backend/types";

/**
 * Opening a support ticket from the phone app.
 *
 * WHAT THIS REPLACED, AND WHY IT HAD TO GO
 *
 * Settings → Help offered three rows, and all three called `window.open` on a
 * `mailto:` — `support@icefall.app` twice and `safety@icefall.app` once. There
 * is no mailbox behind either address. The screen's own disclaimer admitted it
 * ("There is no support desk behind the addresses yet"), which made it honest
 * and useless at the same time: a climber with a real problem composed a mail
 * in their own mail app, sent it, and it went nowhere at all. The failure was
 * invisible to them and invisible to ICEFALL — nobody could even count how many
 * people had tried.
 *
 * THE ONE CALL, AND THE ARGUMENT IT IS NOT ALLOWED TO WIN
 *
 * `open_support_ticket` derives WHO the requester is from `auth.uid()` — company
 * first, then guide, then staff, then athlete — and stamps it on the row. There
 * is deliberately no argument for it. This module must never grow one: a form
 * that asked "what kind of user are you?" is a form somebody can answer
 * wrongly, and the desk would then sort a climber's booking problem into the
 * operator queue on the strength of a mis-tap.
 *
 * WHAT COMES BACK IS PROOF, AND IT IS THE POINT
 *
 * The reference (`ICE-000107`) is generated by a trigger on insert. Showing it
 * is the only way a person can tell that their message was STORED rather than
 * merely accepted by a screen. Nothing in this app may look sent that was not
 * stored — so there is no optimistic success state here, and no local queue
 * that would let the UI say "sent" while the row does not exist.
 *
 * NO SILENT QUEUE, DELIBERATELY. The obvious kindness — keep it on the device
 * and retry later — is the exact thing the honesty doctrine forbids here,
 * because the person walks away believing they have been heard. If it cannot be
 * sent, this module says so and the screen keeps what they typed so they can
 * send it themselves when there is signal.
 */

/* -------------------------------------------------------------------------- */
/* The vocabulary the database will actually accept                            */
/* -------------------------------------------------------------------------- */

/**
 * `support_tickets_type_check` — all ten.
 *
 * THE FUNCTION DOES NOT VALIDATE THIS. `p_type` is passed straight into the
 * INSERT, so an unknown value is caught by the column's CHECK and comes back as
 * a constraint-violation string rather than anything a person should read.
 * Verified against the live database, not inferred: `verification` and
 * `listing` were added by the intake migration, so reading only the original
 * CRM migration gives eight of the ten and a false sense of completeness.
 */
export type SupportType = SupportTicketType;

/**
 * What an ATHLETE is offered, which is not all ten.
 *
 * `verification` and `listing` exist for the guide app — a guide chasing their
 * licence check or their marketplace listing. Offering them here would invite a
 * climber to file into a queue that is not about them. `operator` stays: a
 * climber complaining about an expedition company is exactly that.
 *
 * The order is deliberate. `safety` sits first because a person in danger
 * should not scan a list, and the reason it is a TYPE rather than a separate
 * destination is that there is one desk — a second address would be a second
 * mailbox with nothing behind it, which is what this whole change removes.
 */
export const SUPPORT_TYPES: readonly {
  value: SupportType;
  label: string;
  detail: string;
}[] = [
  {
    value: "safety",
    label: "Safety",
    detail: "Someone or something putting a person at risk. This reaches the same desk as everything else — ICEFALL has one, and it is not staffed around the clock.",
  },
  {
    value: "account",
    label: "My account",
    detail: "Signing in, your handle, your data, closing your account.",
  },
  {
    value: "technical",
    label: "Something is broken",
    detail: "The app is wrong, stuck, or does something you did not ask it to.",
  },
  {
    value: "booking",
    label: "A booking",
    detail: "An enquiry or a booking with a guide or a company.",
  },
  {
    value: "payment",
    label: "Money",
    detail: "ICEFALL takes no payments yet, so this is for questions rather than charges.",
  },
  {
    value: "operator",
    label: "A company",
    detail: "An expedition company listed here.",
  },
  {
    value: "content",
    label: "Something on a page",
    detail: "A mountain, route, trek or figure that looks wrong.",
  },
  { value: "other", label: "Something else", detail: "Anything the list above does not cover." },
];

/** `length(btrim(p_body)) < 10` raises in the database. Match it here or a person meets a DB error. */
export const MIN_BODY_CHARS = 10;

/** The function truncates rather than rejecting, so this is a UI limit, not a rule. */
export const MAX_SUBJECT_CHARS = 200;

/* -------------------------------------------------------------------------- */
/* Honesty copy — rendered verbatim                                            */
/* -------------------------------------------------------------------------- */

/**
 * NO RESPONSE TIME. NOT EVEN A VAGUE ONE.
 *
 * "We usually reply within a day", "typically a few hours", "soon" — every one
 * of them is a number ICEFALL has never measured. The column that would hold it
 * (`first_response_at`) exists and is empty, because nothing has ever been
 * answered. That is not a gap to paper over with a friendly guess; it is the
 * state of the business, and the doctrine's answer to an unmeasurable figure is
 * to say why it is missing rather than to infer one.
 *
 * When there is data, the real number can be stated. Until then, this.
 */
export const SUPPORT_NO_RESPONSE_TIME =
  "ICEFALL does not promise a reply time. Nobody has been answered here yet, so there is no average to quote — when there is one, it will say so rather than estimating.";

/** Shown with the reference, because the reference is the evidence. */
export const SUPPORT_STORED_NOTICE =
  "Your request is stored and has a reference. Keep it — it is how this request is found again, and it is the proof it exists rather than a screen having said so.";

/**
 * The signed-out case, and why it is not a form.
 *
 * The function refuses an anonymous caller at the GRANT — `execute` belongs to
 * `authenticated` only — so an unauthenticated request never reaches the
 * function body and comes back as `42501 permission denied for function`. That
 * string must never reach a climber: it reads as a broken app rather than as a
 * signed-out one. So the screen does not render a form it knows cannot send.
 */
export const SUPPORT_SIGNED_OUT =
  "Support requests are attached to your account, so this needs you to be signed in. That is also how a reply can reach you — without an account there is nowhere for one to go.";

/** No `VITE_SUPABASE_*` in this build. Different from signed out, and said differently. */
export const SUPPORT_NO_BACKEND =
  "This build is not connected to ICEFALL's server, so a request cannot be stored. Nothing you write here would reach anybody.";

/** Offline. Their words are kept; nothing is queued behind their back. */
export const SUPPORT_NOT_SENT =
  "This could not be sent — the device is offline. Nothing has been stored and nothing is waiting in the background, so it has not reached anybody. What you wrote is still here; send it when you have signal.";

/**
 * Abuse reporting is MODERATION, and it is a different thing.
 *
 * Reporting a post or a person goes to `src/social/comments.ts`, which is about
 * removing content and restricting an account. Folding it into support would
 * put "this person is harassing me" into the same queue as "my password reset
 * did not arrive", and the two need different speeds and different powers.
 */
export const SUPPORT_ABUSE_IS_SEPARATE =
  "Reporting a post or a person is a separate thing, done from the post itself — that goes to moderation rather than to support.";

/* -------------------------------------------------------------------------- */
/* The call                                                                    */
/* -------------------------------------------------------------------------- */

export type SupportFailure =
  | "no-backend"
  | "signed-out"
  | "offline"
  | "too-short"
  | "refused";

export type SupportResult =
  | { ok: true; reference: string; id: string; kind: string }
  | { ok: false; reason: SupportFailure; message: string };

/**
 * Postgres speaks to operators, not to climbers.
 *
 * `permission denied for function open_support_ticket` is accurate and unusable.
 * Anything not explicitly recognised here becomes one plain sentence rather
 * than a raw `error.message`, and the caller keeps what the person typed.
 */
function readFailure(code: string | undefined, message: string): {
  reason: SupportFailure;
  message: string;
} {
  const m = message.toLowerCase();

  // The grant, and the in-function guard, are the same situation to a person.
  if (code === "42501" || m.includes("not signed in") || m.includes("permission denied")) {
    return { reason: "signed-out", message: SUPPORT_SIGNED_OUT };
  }
  // The database's own validation sentences are written for a human. Keep them.
  if (m.includes("a little more detail")) {
    return { reason: "too-short", message: "Please describe the problem in a little more detail." };
  }
  if (m.includes("needs a subject")) {
    return { reason: "refused", message: "A support request needs a subject." };
  }
  // fetch failures surface as a TypeError with no code, and mean the same thing
  // to somebody in a hut as `navigator.onLine === false` does.
  if (code === undefined && (m.includes("fetch") || m.includes("network"))) {
    return { reason: "offline", message: SUPPORT_NOT_SENT };
  }
  return {
    reason: "refused",
    message:
      "ICEFALL could not open this request, and it has not been stored. What you wrote is still here — trying again is worth a go.",
  };
}

export async function openSupportTicket(input: {
  subject: string;
  body: string;
  type: SupportType;
  /**
   * Where they were when they asked.
   *
   * TRIAGE METADATA, NEVER AUTHORITY TO ACT. A desk that reads "they were on
   * /settings/membership" as "they want their membership changed" has turned a
   * breadcrumb into an instruction. It records the screen; it never records a
   * request.
   */
  originScreen: string;
}): Promise<SupportResult> {
  if (!supabase) {
    return { ok: false, reason: "no-backend", message: SUPPORT_NO_BACKEND };
  }

  const subject = input.subject.trim();
  const body = input.body.trim();

  if (body.length < MIN_BODY_CHARS) {
    return {
      ok: false,
      reason: "too-short",
      message: `Please describe the problem in a little more detail — at least ${MIN_BODY_CHARS} characters.`,
    };
  }

  // Checked BEFORE the call so an offline attempt says "offline" rather than
  // whatever a dropped fetch happens to look like.
  if (typeof navigator !== "undefined" && navigator.onLine === false) {
    return { ok: false, reason: "offline", message: SUPPORT_NOT_SENT };
  }

  // Signed out is not an error to recover from; it is a different screen. Asked
  // here so the person is told the true reason rather than a permissions string.
  const { data: sess } = await supabase.auth.getSession();
  if (!sess.session) {
    return { ok: false, reason: "signed-out", message: SUPPORT_SIGNED_OUT };
  }

  try {
    const { data, error } = await supabase.rpc("open_support_ticket", {
      p_subject: subject.slice(0, MAX_SUBJECT_CHARS),
      p_body: body,
      p_type: input.type,
      p_origin_app: "phone_app",
      p_origin_screen: input.originScreen.slice(0, 200),
    });

    if (error) {
      const f = readFailure(error.code, error.message ?? "");
      return { ok: false, ...f };
    }

    // Belt and braces: a shape we do not recognise is NOT a success. Saying
    // "sent" on a response we cannot read the reference out of would be exactly
    // the lie this module exists to prevent.
    const row = data as { ok?: boolean; id?: string; reference?: string; kind?: string } | null;
    if (!row?.ok || !row.reference || !row.id) {
      return {
        ok: false,
        reason: "refused",
        message:
          "ICEFALL could not confirm this was stored, so it is not being reported as sent. What you wrote is still here.",
      };
    }

    return { ok: true, reference: row.reference, id: row.id, kind: row.kind ?? "athlete" };
  } catch (e) {
    const f = readFailure(undefined, e instanceof Error ? e.message : String(e));
    return { ok: false, ...f };
  }
}
