/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeeklyRouteImport } from './routes/weekly'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnlyFansRouteImport } from './routes/onlyfans'
import { Route as InstagramRouteImport } from './routes/instagram'
import { Route as RedditRouteImport } from './routes/reddit'
import { Route as XRouteImport } from './routes/x'
import { Route as TiktokRouteImport } from './routes/tiktok'
import { Route as AdsRouteImport } from './routes/ads'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as FacebookRouteImport } from './routes/facebook'
import { Route as ChattersRouteImport } from './routes/chatters'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as ClockRouteImport } from './routes/clock'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as BernardRouteImport } from './routes/bernard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as FinancialsRouteImport } from './routes/financials'
import { Route as RedditAirtableRouteImport } from './routes/reddit-airtable'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as CreatorsCreatorIdRouteImport } from './routes/creators.$creatorId'

const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const FacebookRoute = FacebookRouteImport.update({
  id: '/facebook',
  path: '/facebook',
  getParentRoute: () => rootRouteImport,
} as any)
const ChattersRoute = ChattersRouteImport.update({
  id: '/chatters',
  path: '/chatters',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ClockRoute = ClockRouteImport.update({
  id: '/clock',
  path: '/clock',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const BernardRoute = BernardRouteImport.update({
  id: '/bernard',
  path: '/bernard',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialsRoute = FinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const RedditAirtableRoute = RedditAirtableRouteImport.update({
  id: '/reddit-airtable',
  path: '/reddit-airtable',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WeeklyRoute = WeeklyRouteImport.update({
  id: '/weekly',
  path: '/weekly',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlyFansRoute = OnlyFansRouteImport.update({
  id: '/onlyfans',
  path: '/onlyfans',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramRoute = InstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const RedditRoute = RedditRouteImport.update({
  id: '/reddit',
  path: '/reddit',
  getParentRoute: () => rootRouteImport,
} as any)
const XRoute = XRouteImport.update({
  id: '/x',
  path: '/x',
  getParentRoute: () => rootRouteImport,
} as any)
const TiktokRoute = TiktokRouteImport.update({
  id: '/tiktok',
  path: '/tiktok',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsRoute = AdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsCreatorIdRoute = CreatorsCreatorIdRouteImport.update({
  id: '/creators/$creatorId',
  path: '/creators/$creatorId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/revenue': typeof RevenueRoute
  '/settings': typeof SettingsRoute
  '/weekly': typeof WeeklyRoute
  '/onlyfans': typeof OnlyFansRoute
  '/instagram': typeof InstagramRoute
  '/reddit': typeof RedditRoute
  '/x': typeof XRoute
  '/tiktok': typeof TiktokRoute
  '/ads': typeof AdsRoute
  '/daily': typeof DailyRoute
  '/facebook': typeof FacebookRoute
  '/chatters': typeof ChattersRoute
  '/leads': typeof LeadsRoute
  '/clock': typeof ClockRoute
  '/audit': typeof AuditRoute
  '/automation': typeof AutomationRoute
  '/bernard': typeof BernardRoute
  '/chat': typeof ChatRoute
  '/financials': typeof FinancialsRoute
  '/reddit-airtable': typeof RedditAirtableRoute
  '/p/$slug': typeof PSlugRoute
  '/creators/$creatorId': typeof CreatorsCreatorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/revenue': typeof RevenueRoute
  '/settings': typeof SettingsRoute
  '/weekly': typeof WeeklyRoute
  '/onlyfans': typeof OnlyFansRoute
  '/instagram': typeof InstagramRoute
  '/reddit': typeof RedditRoute
  '/x': typeof XRoute
  '/tiktok': typeof TiktokRoute
  '/ads': typeof AdsRoute
  '/daily': typeof DailyRoute
  '/facebook': typeof FacebookRoute
  '/chatters': typeof ChattersRoute
  '/leads': typeof LeadsRoute
  '/clock': typeof ClockRoute
  '/audit': typeof AuditRoute
  '/automation': typeof AutomationRoute
  '/bernard': typeof BernardRoute
  '/chat': typeof ChatRoute
  '/financials': typeof FinancialsRoute
  '/reddit-airtable': typeof RedditAirtableRoute
  '/p/$slug': typeof PSlugRoute
  '/creators/$creatorId': typeof CreatorsCreatorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/revenue': typeof RevenueRoute
  '/settings': typeof SettingsRoute
  '/weekly': typeof WeeklyRoute
  '/onlyfans': typeof OnlyFansRoute
  '/instagram': typeof InstagramRoute
  '/reddit': typeof RedditRoute
  '/x': typeof XRoute
  '/tiktok': typeof TiktokRoute
  '/ads': typeof AdsRoute
  '/daily': typeof DailyRoute
  '/facebook': typeof FacebookRoute
  '/chatters': typeof ChattersRoute
  '/leads': typeof LeadsRoute
  '/clock': typeof ClockRoute
  '/audit': typeof AuditRoute
  '/automation': typeof AutomationRoute
  '/bernard': typeof BernardRoute
  '/chat': typeof ChatRoute
  '/financials': typeof FinancialsRoute
  '/reddit-airtable': typeof RedditAirtableRoute
  '/p/$slug': typeof PSlugRoute
  '/creators/$creatorId': typeof CreatorsCreatorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/revenue'
    | '/settings'
    | '/weekly'
    | '/onlyfans'
    | '/instagram'
    | '/reddit'
    | '/x'
    | '/tiktok'
    | '/ads'
    | '/daily'
    | '/facebook'
    | '/chatters'
    | '/leads'
    | '/clock'
    | '/audit'
    | '/automation'
    | '/bernard'
    | '/chat'
    | '/financials'
    | '/reddit-airtable'
    | '/p/$slug'
    | '/creators/$creatorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/revenue'
    | '/settings'
    | '/weekly'
    | '/onlyfans'
    | '/instagram'
    | '/reddit'
    | '/x'
    | '/tiktok'
    | '/ads'
    | '/daily'
    | '/facebook'
    | '/chatters'
    | '/leads'
    | '/clock'
    | '/audit'
    | '/automation'
    | '/bernard'
    | '/chat'
    | '/financials'
    | '/reddit-airtable'
    | '/p/$slug'
    | '/creators/$creatorId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/revenue'
    | '/settings'
    | '/weekly'
    | '/onlyfans'
    | '/instagram'
    | '/reddit'
    | '/x'
    | '/tiktok'
    | '/ads'
    | '/daily'
    | '/facebook'
    | '/chatters'
    | '/leads'
    | '/clock'
    | '/audit'
    | '/automation'
    | '/bernard'
    | '/chat'
    | '/financials'
    | '/reddit-airtable'
    | '/p/$slug'
    | '/creators/$creatorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RevenueRoute: typeof RevenueRoute
  SettingsRoute: typeof SettingsRoute
  WeeklyRoute: typeof WeeklyRoute
  OnlyFansRoute: typeof OnlyFansRoute
  InstagramRoute: typeof InstagramRoute
  RedditRoute: typeof RedditRoute
  XRoute: typeof XRoute
  TiktokRoute: typeof TiktokRoute
  AdsRoute: typeof AdsRoute
  DailyRoute: typeof DailyRoute
  FacebookRoute: typeof FacebookRoute
  ChattersRoute: typeof ChattersRoute
  LeadsRoute: typeof LeadsRoute
  ClockRoute: typeof ClockRoute
  AuditRoute: typeof AuditRoute
  AutomationRoute: typeof AutomationRoute
  BernardRoute: typeof BernardRoute
  ChatRoute: typeof ChatRoute
  FinancialsRoute: typeof FinancialsRoute
  RedditAirtableRoute: typeof RedditAirtableRoute
  PSlugRoute: typeof PSlugRoute
  CreatorsCreatorIdRoute: typeof CreatorsCreatorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weekly': {
      id: '/weekly'
      path: '/weekly'
      fullPath: '/weekly'
      preLoaderRoute: typeof WeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onlyfans': {
      id: '/onlyfans'
      path: '/onlyfans'
      fullPath: '/onlyfans'
      preLoaderRoute: typeof OnlyFansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram': {
      id: '/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof InstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reddit': {
      id: '/reddit'
      path: '/reddit'
      fullPath: '/reddit'
      preLoaderRoute: typeof RedditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/x': {
      id: '/x'
      path: '/x'
      fullPath: '/x'
      preLoaderRoute: typeof XRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiktok': {
      id: '/tiktok'
      path: '/tiktok'
      fullPath: '/tiktok'
      preLoaderRoute: typeof TiktokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads': {
      id: '/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facebook': {
      id: '/facebook'
      path: '/facebook'
      fullPath: '/facebook'
      preLoaderRoute: typeof FacebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatters': {
      id: '/chatters'
      path: '/chatters'
      fullPath: '/chatters'
      preLoaderRoute: typeof ChattersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clock': {
      id: '/clock'
      path: '/clock'
      fullPath: '/clock'
      preLoaderRoute: typeof ClockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bernard': {
      id: '/bernard'
      path: '/bernard'
      fullPath: '/bernard'
      preLoaderRoute: typeof BernardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financials': {
      id: '/financials'
      path: '/financials'
      fullPath: '/financials'
      preLoaderRoute: typeof FinancialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reddit-airtable': {
      id: '/reddit-airtable'
      path: '/reddit-airtable'
      fullPath: '/reddit-airtable'
      preLoaderRoute: typeof RedditAirtableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators/$creatorId': {
      id: '/creators/$creatorId'
      path: '/creators/$creatorId'
      fullPath: '/creators/$creatorId'
      preLoaderRoute: typeof CreatorsCreatorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RevenueRoute: RevenueRoute,
  SettingsRoute: SettingsRoute,
  WeeklyRoute: WeeklyRoute,
  OnlyFansRoute: OnlyFansRoute,
  InstagramRoute: InstagramRoute,
  RedditRoute: RedditRoute,
  XRoute: XRoute,
  TiktokRoute: TiktokRoute,
  AdsRoute: AdsRoute,
  DailyRoute: DailyRoute,
  FacebookRoute: FacebookRoute,
  ChattersRoute: ChattersRoute,
  LeadsRoute: LeadsRoute,
  ClockRoute: ClockRoute,
  AuditRoute: AuditRoute,
  AutomationRoute: AutomationRoute,
  BernardRoute: BernardRoute,
  ChatRoute: ChatRoute,
  FinancialsRoute: FinancialsRoute,
  RedditAirtableRoute: RedditAirtableRoute,
  PSlugRoute: PSlugRoute,
  CreatorsCreatorIdRoute: CreatorsCreatorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
