/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeeklyRouteImport } from './routes/weekly'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnlyFansRouteImport } from './routes/onlyfans'
import { Route as InstagramRouteImport } from './routes/instagram'
import { Route as RedditRouteImport } from './routes/reddit'
import { Route as XRouteImport } from './routes/x'
import { Route as AdsRouteImport } from './routes/ads'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as FacebookRouteImport } from './routes/facebook'
import { Route as CreatorsCreatorIdRouteImport } from './routes/creators.$creatorId'

const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const FacebookRoute = FacebookRouteImport.update({
  id: '/facebook',
  path: '/facebook',
  getParentRoute: () => rootRouteImport,
} as any)
const WeeklyRoute = WeeklyRouteImport.update({
  id: '/weekly',
  path: '/weekly',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlyFansRoute = OnlyFansRouteImport.update({
  id: '/onlyfans',
  path: '/onlyfans',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramRoute = InstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const RedditRoute = RedditRouteImport.update({
  id: '/reddit',
  path: '/reddit',
  getParentRoute: () => rootRouteImport,
} as any)
const XRoute = XRouteImport.update({
  id: '/x',
  path: '/x',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsRoute = AdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsCreatorIdRoute = CreatorsCreatorIdRouteImport.update({
  id: '/creators/$creatorId',
  path: '/creators/$creatorId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/revenue': typeof RevenueRoute
  '/settings': typeof SettingsRoute
  '/weekly': typeof WeeklyRoute
  '/onlyfans': typeof OnlyFansRoute
  '/instagram': typeof InstagramRoute
  '/reddit': typeof RedditRoute
  '/x': typeof XRoute
  '/ads': typeof AdsRoute
  '/daily': typeof DailyRoute
  '/facebook': typeof FacebookRoute
  '/creators/$creatorId': typeof CreatorsCreatorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/revenue': typeof RevenueRoute
  '/settings': typeof SettingsRoute
  '/weekly': typeof WeeklyRoute
  '/onlyfans': typeof OnlyFansRoute
  '/instagram': typeof InstagramRoute
  '/reddit': typeof RedditRoute
  '/x': typeof XRoute
  '/ads': typeof AdsRoute
  '/daily': typeof DailyRoute
  '/facebook': typeof FacebookRoute
  '/creators/$creatorId': typeof CreatorsCreatorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/revenue': typeof RevenueRoute
  '/settings': typeof SettingsRoute
  '/weekly': typeof WeeklyRoute
  '/onlyfans': typeof OnlyFansRoute
  '/instagram': typeof InstagramRoute
  '/reddit': typeof RedditRoute
  '/x': typeof XRoute
  '/ads': typeof AdsRoute
  '/daily': typeof DailyRoute
  '/facebook': typeof FacebookRoute
  '/creators/$creatorId': typeof CreatorsCreatorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/revenue'
    | '/settings'
    | '/weekly'
    | '/onlyfans'
    | '/instagram'
    | '/reddit'
    | '/x'
    | '/ads'
    | '/daily'
    | '/facebook'
    | '/creators/$creatorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/revenue'
    | '/settings'
    | '/weekly'
    | '/onlyfans'
    | '/instagram'
    | '/reddit'
    | '/x'
    | '/ads'
    | '/daily'
    | '/facebook'
    | '/creators/$creatorId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/revenue'
    | '/settings'
    | '/weekly'
    | '/onlyfans'
    | '/instagram'
    | '/reddit'
    | '/x'
    | '/ads'
    | '/daily'
    | '/facebook'
    | '/creators/$creatorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RevenueRoute: typeof RevenueRoute
  SettingsRoute: typeof SettingsRoute
  WeeklyRoute: typeof WeeklyRoute
  OnlyFansRoute: typeof OnlyFansRoute
  InstagramRoute: typeof InstagramRoute
  RedditRoute: typeof RedditRoute
  XRoute: typeof XRoute
  AdsRoute: typeof AdsRoute
  DailyRoute: typeof DailyRoute
  FacebookRoute: typeof FacebookRoute
  CreatorsCreatorIdRoute: typeof CreatorsCreatorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weekly': {
      id: '/weekly'
      path: '/weekly'
      fullPath: '/weekly'
      preLoaderRoute: typeof WeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onlyfans': {
      id: '/onlyfans'
      path: '/onlyfans'
      fullPath: '/onlyfans'
      preLoaderRoute: typeof OnlyFansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram': {
      id: '/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof InstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reddit': {
      id: '/reddit'
      path: '/reddit'
      fullPath: '/reddit'
      preLoaderRoute: typeof RedditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/x': {
      id: '/x'
      path: '/x'
      fullPath: '/x'
      preLoaderRoute: typeof XRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads': {
      id: '/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facebook': {
      id: '/facebook'
      path: '/facebook'
      fullPath: '/facebook'
      preLoaderRoute: typeof FacebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators/$creatorId': {
      id: '/creators/$creatorId'
      path: '/creators/$creatorId'
      fullPath: '/creators/$creatorId'
      preLoaderRoute: typeof CreatorsCreatorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RevenueRoute: RevenueRoute,
  SettingsRoute: SettingsRoute,
  WeeklyRoute: WeeklyRoute,
  OnlyFansRoute: OnlyFansRoute,
  InstagramRoute: InstagramRoute,
  RedditRoute: RedditRoute,
  XRoute: XRoute,
  AdsRoute: AdsRoute,
  DailyRoute: DailyRoute,
  FacebookRoute: FacebookRoute,
  CreatorsCreatorIdRoute: CreatorsCreatorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
