import { useEffect } from "react";
import {
  motion,
  useMotionTemplate,
  useMotionValue,
  useReducedMotion,
  useSpring,
} from "framer-motion";
import { IcefallMark } from "@/components/ui/IcefallMark";
import { cn } from "@/lib/utils";

/**
 * The closed Mountain Passport.
 *
 * Built entirely in CSS so it stays crisp at any size and inherits the app's
 * one dark palette — a bitmap of a passport would age badly and could not carry
 * the athlete's own name.
 *
 * WHAT THE COVER IS ALLOWED TO SAY
 * --------------------------------
 * ICEFALL has no verification system: no GPS-confirmed summit, no guide
 * attestation, no identity check. A passport is a credential, and a credential
 * nobody checked is worse than none at all — this booklet may be shown to a
 * guide or an operator deciding whether the bearer is competent. So the cover
 * carries the bearer's NAME and a RECORD NUMBER and nothing else that could be
 * mistaken for an authority's endorsement. There is no crest of office, no
 * "verified", no issuing-country line. The word ICEFALL appears as the maker of
 * the booklet, never as its guarantor; the identity page inside states plainly
 * that every entry was added by the bearer.
 *
 * The record number is deliberately NOT called a passport number. It is derived
 * on this device from facts the athlete already gave us, so it is stable across
 * reloads, but nobody issued it and nobody can check it.
 *
 * The cover never derives that number itself. It is generated once, in
 * `src/passport/model.ts`, and passed in — a second derivation here would be a
 * second numbering scheme, and a document that prints two different reference
 * numbers for the same athlete is worse than one that prints none.
 */

/* -------------------------------------------------------------------------- */
/* Types                                                                       */
/* -------------------------------------------------------------------------- */

/**
 * The identity printed on the booklet.
 *
 * The minimum the cover and identity page need, and nothing more. Declared
 * structurally rather than imported from `@/passport/model` so the two files
 * can be worked on independently: the model's richer `PassportIdentity`
 * satisfies this shape, and the book accepts it unchanged.
 *
 * `homeBase` is optional and, today, never supplied. ICEFALL holds a home base
 * on the athlete fixture, but onboarding has never asked for one, so printing
 * it here would put a demo city on a document a guide might read. Until the app
 * genuinely collects it the identity page renders the absence instead.
 */
export interface PassportBearer {
  /** The athlete's name exactly as they entered it. Never reformatted. */
  name: string;
  /** ISO date the local ICEFALL record was opened. */
  memberSince: string;
  /**
   * A stable local record number, generated by `@/passport/model`. NOT an
   * identity document number — see the note at the top of this file.
   */
  expeditionId: string;
  /** e.g. "Chamonix, France", once the athlete has actually stated one. */
  homeBase?: string;
}

/* -------------------------------------------------------------------------- */
/* Type faces                                                                  */
/* -------------------------------------------------------------------------- */

/**
 * The technical face, shared with the booklet's interior.
 *
 * Declared here rather than as a Tailwind class because the ICEFALL theme only
 * registers `sans` and `serif`: a `font-mono` utility would silently fall back
 * to Inter Tight and the record number would lose the tabular, instrument-panel
 * character the whole booklet depends on.
 */
export const TECHNICAL_FAMILY =
  'ui-monospace, "SF Mono", SFMono-Regular, Menlo, Consolas, monospace';

/**
 * Layered near-black, warmed very slightly, with light falling from the upper
 * left. Three stacked gradients rather than one so the cover reads as a
 * material with a surface, not as a flat swatch.
 */
const LEATHER =
  "radial-gradient(125% 90% at 26% 4%, oklch(0.268 0.008 250 / 92%) 0%, transparent 56%)," +
  "radial-gradient(95% 75% at 86% 104%, oklch(0.205 0.010 268 / 78%) 0%, transparent 62%)," +
  "linear-gradient(158deg, oklch(0.208 0.006 250) 0%, oklch(0.160 0.006 246) 54%, oklch(0.130 0.006 240) 100%)";

/* -------------------------------------------------------------------------- */
/* PassportCover                                                               */
/* -------------------------------------------------------------------------- */

export function PassportCover({
  bearer,
  onPress,
  expanded,
  tilt = true,
  dense = false,
  buttonRef,
  className,
}: {
  bearer: PassportBearer;
  /** Provided by the book. When absent the cover renders as inert artwork. */
  onPress?: () => void;
  /** Mirrors the book's open state onto the control for assistive tech. */
  expanded?: boolean;
  /** The book switches this off while the passport is open or animating. */
  tilt?: boolean;
  /**
   * The half-width cover, for the two-column panel on Profile.
   *
   * The full cover is drawn for a ~300px booklet: at half that its margins and
   * type overflow the sheet and the record number falls off the bottom edge.
   * This is the same object at the same proportions with the crest, the rule
   * and the type stepped down — not a different cover, and nothing is dropped.
   */
  dense?: boolean;
  buttonRef?: React.Ref<HTMLButtonElement>;
  className?: string;
}) {
  const reduce = useReducedMotion();
  // Parallax is pure decoration, so it is the first thing to go: under
  // `prefers-reduced-motion` no pointer listener is attached at all, rather
  // than attaching one and animating to zero.
  const live = tilt && !reduce;

  // Raw pointer-derived targets, smoothed by springs so the cover has weight
  // and never snaps to the cursor.
  const targetRotateY = useMotionValue(0);
  const targetRotateX = useMotionValue(0);
  const spring = { stiffness: 150, damping: 20, mass: 0.7 };
  const rotateY = useSpring(targetRotateY, spring);
  const rotateX = useSpring(targetRotateX, spring);

  // The specular highlight tracks the pointer in per-cent of the cover.
  const sheenX = useMotionValue(50);
  const sheenY = useMotionValue(28);
  const sheen = useMotionTemplate`radial-gradient(circle 190px at ${sheenX}% ${sheenY}%, oklch(1 0 0 / 7.5%), transparent 70%)`;

  const rest = () => {
    targetRotateY.set(0);
    targetRotateX.set(0);
    sheenX.set(50);
    sheenY.set(28);
  };

  // Returning to rest when the book takes over stops a half-tilted cover from
  // being carried into the opening rotation, which would look like a glitch.
  useEffect(() => {
    if (!live) rest();
    // `rest` is stable in practice (motion values are stable identities); the
    // dependency that matters is whether tilt is live at all.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [live]);

  const handleMove = (e: React.PointerEvent<HTMLElement>) => {
    if (!live) return;
    const r = e.currentTarget.getBoundingClientRect();
    const x = (e.clientX - r.left) / r.width;
    const y = (e.clientY - r.top) / r.height;
    // Small angles on purpose. This should read as a held object catching the
    // light, not as a card flipping about.
    targetRotateY.set((x - 0.5) * 9);
    targetRotateX.set((0.5 - y) * 7);
    sheenX.set(x * 100);
    sheenY.set(y * 100);
  };

  const face = (
    <>
      {/* Material. Clipped, and deliberately a sibling of the content rather
          than its parent: `overflow: hidden` forces `transform-style: flat`, so
          wrapping the content in it would kill the parallax depth below. */}
      <div
        aria-hidden="true"
        className="grain absolute inset-0 overflow-hidden rounded-card"
        style={{ background: LEATHER }}
      >
        {reduce ? null : <motion.div className="absolute inset-0" style={{ background: sheen }} />}
        {/* Binding. A darker strip down the spine edge, where a real booklet
            folds and where the cover will pivot when it opens. */}
        <div
          className="absolute inset-y-0 left-0 w-[11px]"
          style={{
            background:
              "linear-gradient(90deg, oklch(0 0 0 / 46%) 0%, oklch(0 0 0 / 16%) 55%, transparent 100%)",
          }}
        />
        {/* Stitched edge — one dashed hairline, nothing more. */}
        <div className="absolute inset-[9px] rounded-[8px] border border-dashed border-white/[0.055]" />
        <div className="absolute inset-[5px] rounded-[10px] border border-white/[0.022]" />
      </div>

      {/* Edge light, drawn over the material so the corner catches. */}
      <div
        aria-hidden="true"
        className="pointer-events-none absolute inset-0 rounded-card border border-white/[0.065]"
      />

      {/* Content. `preserve-3d` here is what makes the tilt feel like relief:
          the crest sits proud of the leather and slides against it. */}
      <div
        className={cn(
          "relative flex h-full flex-col items-center justify-between text-center",
          dense ? "px-3 py-4" : "px-6 py-7",
        )}
        style={{ transformStyle: "preserve-3d" }}
      >
        <div
          className={cn(
            "font-light leading-none text-azure/60",
            dense ? "text-[7.5px] tracking-[0.3em]" : "text-[10px] tracking-[0.44em]",
          )}
          style={{ transform: "translateZ(9px)", paddingLeft: dense ? "0.3em" : "0.44em" }}
        >
          ICEFALL
        </div>

        <div className="flex flex-col items-center" style={{ transform: "translateZ(19px)" }}>
          {/* Embossed mark: a shadow copy pushed down, a highlight copy pulled
              up, and a low-contrast face between them. Light from above, as it
              falls on the rest of the cover. */}
          <span
            aria-hidden="true"
            className={cn("relative block", dense ? "h-[32px] w-[54px]" : "h-[52px] w-[88px]")}
          >
            <IcefallMark className="absolute inset-0 h-full w-full translate-y-[1.5px] text-black opacity-70" />
            <IcefallMark className="absolute inset-0 h-full w-full -translate-y-[1.2px] text-white opacity-[0.13]" />
            <IcefallMark className="absolute inset-0 h-full w-full text-white opacity-[0.07]" />
          </span>

          <span
            aria-hidden="true"
            className={cn("block h-px", dense ? "mt-3 w-[34px]" : "mt-5 w-[54px]")}
            style={{
              background: "linear-gradient(90deg, transparent, var(--ice-azure) 50%, transparent)",
              opacity: 0.7,
            }}
          />

          <p
            className={cn(
              "section-label text-mist",
              dense ? "mt-3 text-[7px] tracking-[0.22em]" : "mt-5 text-[9.5px] tracking-[0.3em]",
            )}
          >
            Mountain Passport
          </p>
        </div>

        <div className="flex flex-col items-center" style={{ transform: "translateZ(8px)" }}>
          <p
            className={cn(
              "display max-w-full truncate leading-none text-snow/90",
              dense ? "text-[14px]" : "text-[19px]",
            )}
          >
            {bearer.name}
          </p>
          <p
            className={cn(
              "tnum leading-none text-mist-dim",
              dense ? "mt-1.5 text-[6.5px] tracking-[0.1em]" : "mt-2.5 text-[9px] tracking-[0.16em]",
            )}
            style={{ fontFamily: TECHNICAL_FAMILY }}
          >
            No. {bearer.expeditionId}
          </p>
        </div>
      </div>
    </>
  );

  const shell = cn("relative block h-full w-full select-none", className);
  // `transformPerspective` keeps the tilt correct whether or not an ancestor
  // supplies a perspective, so the cover looks the same standing alone as it
  // does inside the book.
  const transform = {
    rotateX,
    rotateY,
    transformPerspective: 900,
    transformStyle: "preserve-3d" as const,
  };

  if (!onPress) {
    return (
      <motion.div
        className={shell}
        style={transform}
        onPointerMove={handleMove}
        onPointerLeave={rest}
      >
        {face}
      </motion.div>
    );
  }

  return (
    <motion.button
      ref={buttonRef}
      type="button"
      onClick={onPress}
      aria-expanded={expanded}
      className={cn(shell, "text-left")}
      style={transform}
      onPointerMove={handleMove}
      onPointerLeave={rest}
      // Tactile, not bouncy: a press should feel like the booklet giving very
      // slightly under a thumb.
      whileTap={reduce ? undefined : { scale: 0.985 }}
      transition={{ duration: 0.16, ease: [0.22, 1, 0.36, 1] }}
    >
      {face}
      <span className="sr-only">Open your mountain passport</span>
    </motion.button>
  );
}
