/**
 * The database, in TypeScript.
 *
 * Hand-written to match `icefall-supabase/migrations`. Regenerate with
 * `supabase gen types typescript` once the project is linked, and keep the
 * ALIAS form below when you do.
 *
 * `Database` MUST be a `type`, never an `interface`. An interface here type-checks
 * fine and then silently breaks every `.rpc()` call at the point of use, because
 * the client's generics expect a structural alias. This has cost a day before.
 */

export type IcefallRole = "athlete" | "guide" | "operator" | "admin";
export type Availability = "available" | "limited" | "unavailable";
export type ThreadStatus = "open" | "closed";

/**
 * `support_tickets_type_check` — all ten, in the order the constraint lists
 * them. `verification` and `listing` were ADDED by the intake migration for the
 * guide app; a reader of the original CRM migration alone finds eight and
 * believes that is the set.
 */
export type SupportTicketType =
  | "account"
  | "booking"
  | "payment"
  | "content"
  | "operator"
  | "safety"
  | "technical"
  | "verification"
  | "listing"
  | "other";

/** `support_tickets_origin_app_known`. Validated inside the function, unlike the type. */
export type SupportOriginApp = "phone_app" | "web" | "guide_app" | "operator_portal" | "crm";

/** Who the DATABASE decided the requester was. Never sent by a client. */
export type SupportRequesterKind = "athlete" | "guide" | "company" | "staff" | "visitor";

/**
 * What `open_support_ticket` returns.
 *
 * `reference` is generated by a BEFORE INSERT trigger from a sequence, so
 * holding one is proof the row exists. It is the only evidence an app has that
 * a request was stored rather than merely typed.
 */
/**
 * What `open_enquiry` returns — and why nothing renders it.
 *
 * `id` is a raw uuid, NOT a quotable reference. There is no `ICE-000107` in
 * this schema. Showing a uuid would be a fabricated receipt: it has the shape
 * of a reference and none of the use, because the sender cannot quote it to
 * anybody who could look it up for them.
 *
 * The signed-in athlete's real proof is that they can read their own row back —
 * a "My enquiries" surface is the honest home of that, not a code on a toast.
 */
export type EnquiryOpened = {
  ok: true;
  id: string;
};

export type SupportTicketOpened = {
  ok: true;
  id: string;
  reference: string;
  kind: SupportRequesterKind;
};

export type Profile = {
  id: string;
  role: IcefallRole;
  display_name: string;
  avatar_url: string | null;
  /**
   * The public handle. NULL until the person picks one — which for a Google or
   * Apple signup is AFTER the account already exists, because you get a session
   * before anybody can be asked a question. Nullable in the column for exactly
   * that reason; see 20260830100000_identity_username_location.sql.
   */
  username: string | null;
  /** A town or region, as typed. Never an address, never geocoded. */
  location_label: string | null;
  /** ISO 3166-1 alpha-2, or null for "prefer not to say". */
  country_code: string | null;
  created_at: string;
  updated_at: string;
};

/**
 * The onboarding answers. A SEPARATE TABLE, not columns on `profiles`, because
 * `profiles_select` is `using (true)` — body mass, height and birth year there
 * would be readable by every account on the platform.
 */
export type AthleteProfile = {
  id: string;
  experience: string | null;
  body_mass_kg: number | null;
  height_cm: number | null;
  birth_year: number | null;
  typical_session_min: number | null;
  training_days: number[];
  max_altitude_m: number | null;
  answers: Record<string, unknown>;
  answers_version: number;
  onboarded_at: string | null;
  created_at: string;
  updated_at: string;
};

/** What `claim_username` and `username_available` return. */
export type UsernameVerdict = {
  ok: boolean;
  reason?: "format" | "reserved" | "taken";
  username?: string;
  suggestions?: string[];
};

export type GuideProfile = {
  id: string;
  headline: string | null;
  based_in: string | null;
  specialities: string[];
  mountains: string[];
  languages: string[];
  years_guiding: number | null;
  daily_rate_eur: number | null;
  availability: Availability;
  bio: string | null;
  /** Always false. The database enforces it — see the migration. */
  /* `credentials_verified` was declared here and is REMOVED. Session 03 is
     dropping the column rather than unpinning it: a stored TRUE that outlives
     the certificate's expiry is the lapsed-insurance bug one layer down. State
     is derived in the database by `guide_credentials_state()` →
     unchecked | checked | expired, and in this app by `guides/verification.ts`.
     Declaring it here would let new code compile against a column that does not
     exist and read `undefined` forever — harmless, because undefined fails
     closed, but silent. */
  listed: boolean;
  created_at: string;
  updated_at: string;
};

export type OperatorProfile = {
  id: string;
  company_name: string;
  certification: string | null;
  regions: string[];
  min_elevation_m: number | null;
  response_hours: number | null;
  blurb: string | null;
  listed: boolean;
  created_at: string;
  updated_at: string;
};

export type Thread = {
  id: string;
  peak_name: string | null;
  peak_elevation_m: number | null;
  from_date: string | null;
  to_date: string | null;
  group_size: number | null;
  status: ThreadStatus;
  created_by: string;
  created_at: string;
  last_message_at: string;
};

export type ThreadParticipant = {
  thread_id: string;
  profile_id: string;
  last_read_at: string | null;
  joined_at: string;
};

export type Message = {
  id: string;
  thread_id: string;
  sender_id: string;
  body: string;
  created_at: string;
};

type Table<Row, Insert = Partial<Row>, Update = Partial<Row>> = {
  Row: Row;
  Insert: Insert;
  Update: Update;
  Relationships: [];
};

export type Database = {
  public: {
    Tables: {
      profiles: Table<Profile, Pick<Profile, "id" | "display_name">>;
      athlete_profiles: Table<AthleteProfile, Pick<AthleteProfile, "id"> & Partial<AthleteProfile>>;
      guide_profiles: Table<GuideProfile, Pick<GuideProfile, "id"> & Partial<GuideProfile>>;
      operator_profiles: Table<
        OperatorProfile,
        Pick<OperatorProfile, "id" | "company_name"> & Partial<OperatorProfile>
      >;
      threads: Table<Thread, Pick<Thread, "created_by"> & Partial<Thread>>;
      thread_participants: Table<
        ThreadParticipant,
        Pick<ThreadParticipant, "thread_id" | "profile_id">
      >;
      messages: Table<Message, Pick<Message, "thread_id" | "sender_id" | "body">>;
    };
    Views: Record<never, never>;
    Functions: {
      is_admin: { Args: Record<never, never>; Returns: boolean };
      my_role: { Args: Record<never, never>; Returns: IcefallRole };
      is_thread_participant: { Args: { t: string }; Returns: boolean };
      /**
       * ADVISORY. Stale the moment it returns — two people can both be told a
       * name is free. `claim_username` is the one that decides.
       */
      username_available: { Args: { candidate: string }; Returns: UsernameVerdict };
      /**
       * The only call that decides. Converts a unique-violation into
       * `{ok:false, reason:'taken'}` rather than raising, so no caller has to
       * read a Postgres error string.
       */
      claim_username: { Args: { candidate: string }; Returns: UsernameVerdict };
      set_my_location: {
        Args: { p_label: string | null; p_country: string | null };
        Returns: { ok: boolean; reason?: string };
      };
      /**
       * Open a support ticket. The ONLY sanctioned path for a signed-in person.
       *
       * NO ARGUMENT FOR WHO IS ASKING, AND THAT IS THE DESIGN. The function
       * derives the requester from `auth.uid()` — company, then guide, then
       * staff, then athlete — and stamps `requester_kind` on the row. A caller
       * cannot pass one, so a mis-tapped chooser cannot route a climber's
       * problem into the operator queue.
       *
       * `execute` is granted to `authenticated` only. An anonymous call is
       * refused at the GRANT and returns `42501 permission denied for function`
       * without ever reaching the body's own `not signed in` check — so a
       * caller that surfaces `error.message` shows a Postgres permission string
       * to a climber. Handle 42501 as "signed out"; see `support/tickets.ts`.
       *
       * `p_type` is NOT validated here. It goes straight into the INSERT and is
       * caught by `support_tickets_type_check`, so an unknown value returns a
       * constraint violation rather than anything readable.
       */
      accept_invitations: {
        Args: Record<string, never>;
        Returns: number;
      };
      open_support_ticket: {
        Args: {
          p_subject: string;
          p_body: string;
          p_type?: SupportTicketType;
          p_origin_app?: SupportOriginApp;
          p_origin_screen?: string | null;
        };
        Returns: SupportTicketOpened;
      };
      /**
       * HEALTH-DATA CONSENT. Three calls, and the split matters.
       *
       * `health_consent_wording_in_force` hands back the sentence to PUT ON THE
       * SCREEN. `health_record_consent` takes no version: it stamps whatever is
       * in force at write time, so a stale build cannot record agreement to
       * words nobody was shown. `health_my_consent` reads back the decision
       * with the frozen sentence it was made against.
       *
       * `p_decision` of 'withdrawn' or 'declined' DELETES every stored
       * measurement inside the same transaction. That is not a side effect to
       * be surprised by — it is the erasure Article 17 requires, placed where a
       * caller cannot forget it.
       */
      health_consent_wording_in_force: {
        Args: { p_purpose: string };
        Returns: { version: string; wording: string }[];
      };
      health_record_consent: {
        Args: { p_purpose: string; p_decision: string; p_route?: string };
        Returns: number;
      };
      health_my_consent: {
        Args: { p_purpose: string };
        Returns: {
          decision: string;
          version: string | null;
          wording: string | null;
          recorded_at: string;
        }[];
      };
      open_enquiry: {
        Args: {
          p_body: string;
          p_product_id?: string | null;
          /**
           * TEXT, not a uuid. Mountains and treks are not tables — they resolve
           * through `destinations`, which is why this one is a slug.
           */
          p_destination_id?: string | null;
          p_company_id?: string | null;
          p_origin_app?: SupportOriginApp;
          p_origin_screen?: string | null;
        };
        Returns: EnquiryOpened;
      };
      /**
       * STRAVA. Two calls, and both are deliberately tiny.
       *
       * `strava_status` returns a SET — Postgres `returns table`, so supabase-js
       * hands back an array that is empty when nothing is connected. There is no
       * "connected: false" row; absence IS the answer, which is why `Returns` is
       * an array type here and every caller reads `data[0] ?? null`.
       *
       * IT CARRIES NO TOKEN, AND THIS TYPE IS PART OF THAT GUARANTEE. If a
       * future change adds `access_token` to the SQL, this shape is the second
       * place it would have to be added — see the header of
       * `icefall-supabase/migrations/20260907140000_strava_connection.sql`.
       *
       * `strava_disconnect` forgets the row and nothing else. It CANNOT
       * deauthorise at Strava — only the Edge Function can, holding the client
       * secret — so a caller that uses it alone has revoked ICEFALL's copy of a
       * token that Strava still honours. It exists for the one case the function
       * cannot serve: a token Strava has already revoked, where deauthorising
       * answers 401 forever and the row would otherwise be unremovable.
       */
      strava_status: {
        Args: Record<never, never>;
        Returns: {
          connected: boolean;
          /** NULL when Strava's token response did not identify the athlete. */
          athlete_id: number | null;
          athlete_username: string | null;
          scope: string;
          connected_at: string;
        }[];
      };
      strava_disconnect: { Args: Record<never, never>; Returns: undefined };
      /**
       * WATCH ACCOUNTS (COROS, Polar, Suunto, Garmin). Same two-call shape as
       * `strava_status` / `strava_disconnect`, generalised to a table because
       * a person can connect more than one watch service at once.
       *
       * `watch_status` returns a SET — one row per connected provider, empty
       * when nothing is connected. Absence IS the answer, same as Strava:
       * there is no `connected: false` row, and it carries no token material.
       *
       * `watch_disconnect` forgets one row, by provider. It CANNOT revoke at
       * the vendor — only the Edge Function can, holding the client
       * credentials — so it exists for the one case the function cannot
       * serve: a token the vendor has already revoked.
       */
      watch_status: {
        Args: Record<never, never>;
        Returns: {
          provider: "garmin" | "coros" | "suunto" | "polar";
          provider_user_id: string | null;
          account_label: string | null;
          scope: string;
          region: "eu" | "us" | null;
          connected_at: string;
        }[];
      };
      watch_disconnect: { Args: { p_provider: string }; Returns: undefined };
    };
    Enums: {
      icefall_role: IcefallRole;
    };
    CompositeTypes: Record<never, never>;
  };
};
