/**
 * The database, in TypeScript.
 *
 * Hand-written to match `icefall-supabase/migrations`. Regenerate with
 * `supabase gen types typescript` once the project is linked, and keep the
 * ALIAS form below when you do.
 *
 * `Database` MUST be a `type`, never an `interface`. An interface here type-checks
 * fine and then silently breaks every `.rpc()` call at the point of use, because
 * the client's generics expect a structural alias. This has cost a day before.
 */

export type IcefallRole = "athlete" | "guide" | "operator" | "admin";
export type Availability = "available" | "limited" | "unavailable";
export type ThreadStatus = "open" | "closed";

/**
 * `support_tickets_type_check` — all ten, in the order the constraint lists
 * them. `verification` and `listing` were ADDED by the intake migration for the
 * guide app; a reader of the original CRM migration alone finds eight and
 * believes that is the set.
 */
export type SupportTicketType =
  | "account"
  | "booking"
  | "payment"
  | "content"
  | "operator"
  | "safety"
  | "technical"
  | "verification"
  | "listing"
  | "other";

/** `support_tickets_origin_app_known`. Validated inside the function, unlike the type. */
export type SupportOriginApp = "phone_app" | "web" | "guide_app" | "operator_portal" | "crm";

/** Who the DATABASE decided the requester was. Never sent by a client. */
export type SupportRequesterKind = "athlete" | "guide" | "company" | "staff" | "visitor";

/**
 * What `open_support_ticket` returns.
 *
 * `reference` is generated by a BEFORE INSERT trigger from a sequence, so
 * holding one is proof the row exists. It is the only evidence an app has that
 * a request was stored rather than merely typed.
 */
/**
 * What `open_enquiry` returns — and why nothing renders it.
 *
 * `id` is a raw uuid, NOT a quotable reference. There is no `ICE-000107` in
 * this schema. Showing a uuid would be a fabricated receipt: it has the shape
 * of a reference and none of the use, because the sender cannot quote it to
 * anybody who could look it up for them.
 *
 * The signed-in athlete's real proof is that they can read their own row back —
 * a "My enquiries" surface is the honest home of that, not a code on a toast.
 */
export type EnquiryOpened = {
  ok: true;
  id: string;
};

export type SupportTicketOpened = {
  ok: true;
  id: string;
  reference: string;
  kind: SupportRequesterKind;
};

export type Profile = {
  id: string;
  role: IcefallRole;
  display_name: string;
  avatar_url: string | null;
  /**
   * The public handle. NULL until the person picks one — which for a Google or
   * Apple signup is AFTER the account already exists, because you get a session
   * before anybody can be asked a question. Nullable in the column for exactly
   * that reason; see 20260830100000_identity_username_location.sql.
   */
  username: string | null;
  /** A town or region, as typed. Never an address, never geocoded. */
  location_label: string | null;
  /** ISO 3166-1 alpha-2, or null for "prefer not to say". */
  country_code: string | null;
  created_at: string;
  updated_at: string;
};

/**
 * The onboarding answers. A SEPARATE TABLE, not columns on `profiles`, because
 * `profiles_select` is `using (true)` — body mass, height and birth year there
 * would be readable by every account on the platform.
 */
export type AthleteProfile = {
  id: string;
  experience: string | null;
  body_mass_kg: number | null;
  height_cm: number | null;
  birth_year: number | null;
  typical_session_min: number | null;
  training_days: number[];
  max_altitude_m: number | null;
  answers: Record<string, unknown>;
  answers_version: number;
  onboarded_at: string | null;
  created_at: string;
  updated_at: string;
};

/** What `claim_username` and `username_available` return. */
export type UsernameVerdict = {
  ok: boolean;
  reason?: "format" | "reserved" | "taken";
  username?: string;
  suggestions?: string[];
};

export type GuideProfile = {
  id: string;
  headline: string | null;
  based_in: string | null;
  specialities: string[];
  mountains: string[];
  languages: string[];
  years_guiding: number | null;
  daily_rate_eur: number | null;
  availability: Availability;
  bio: string | null;
  /** Always false. The database enforces it — see the migration. */
  /* `credentials_verified` was declared here and is REMOVED. Session 03 is
     dropping the column rather than unpinning it: a stored TRUE that outlives
     the certificate's expiry is the lapsed-insurance bug one layer down. State
     is derived in the database by `guide_credentials_state()` →
     unchecked | checked | expired, and in this app by `guides/verification.ts`.
     Declaring it here would let new code compile against a column that does not
     exist and read `undefined` forever — harmless, because undefined fails
     closed, but silent. */
  listed: boolean;
  created_at: string;
  updated_at: string;
};

export type OperatorProfile = {
  id: string;
  company_name: string;
  certification: string | null;
  regions: string[];
  min_elevation_m: number | null;
  response_hours: number | null;
  blurb: string | null;
  listed: boolean;
  created_at: string;
  updated_at: string;
};

/**
 * `threads.kind` — 20260818090000_chat.sql.
 *
 * PINNED AT CREATION. `threads_guard` refuses any UPDATE that changes it, so
 * this is decided once, by whoever inserts the row, and never again.
 */
export type ThreadKind = "direct" | "group" | "enquiry";

export type Thread = {
  id: string;
  peak_name: string | null;
  peak_elevation_m: number | null;
  from_date: string | null;
  to_date: string | null;
  group_size: number | null;
  status: ThreadStatus;
  created_by: string;
  created_at: string;
  last_message_at: string;
  /** Added 20260818090000. Defaults to 'enquiry' — a person-to-person thread must say so. */
  kind: ThreadKind;
  /** Groups only. `threads_guard` raises on a retitle of anything else. */
  title: string | null;
};

export type ThreadParticipant = {
  thread_id: string;
  profile_id: string;
  last_read_at: string | null;
  joined_at: string;
};

export type MessageKind = "text" | "image" | "voice" | "file" | "system";

export type Message = {
  id: string;
  thread_id: string;
  sender_id: string;
  /**
   * NULLABLE since 20260818090000. `messages_body_present` requires words on a
   * text message and an attachment on anything else, so a picture has no body.
   */
  body: string | null;
  created_at: string;
  kind: MessageKind;
  /**
   * THE DEVICE'S OWN ID, minted before the first send attempt and kept across
   * retries. A partial unique index on `(sender_id, client_id)` is what makes
   * an offline queue safe: the second attempt conflicts instead of duplicating.
   * Null on a server-generated system message, which needs no such key.
   */
  client_id: string | null;
  attachment_path: string | null;
  attachment_meta: Record<string, unknown> | null;
};

/**
 * `public.products` — the marketplace, and the ONLY way this app can honestly
 * name a company.
 *
 * An athlete may read a row only while `status = 'live'` (`products_select`,
 * 20260828110000:968). `company_id` is a real uuid, which is what makes an
 * enquiry about a product resolvable to a company when an enquiry about a
 * mountain is not — see the header of `enquiries/send.ts` for why the operator
 * slugs in `services/operators.ts` can never be.
 *
 * Only the four columns this app actually reads are declared. A wider type
 * would invite a wider select, and `price_state`, `availability_state` and the
 * rest belong to screens that do not exist here.
 */
export type MarketplaceProduct = {
  id: string;
  company_id: string;
  name: string;
  status: "draft" | "pending_review" | "live" | "archived";
};

/** `public.product_destinations` — which mountains a product goes to. */
export type ProductDestination = {
  product_id: string;
  destination_id: string;
};

/**
 * `public.readiness_shares` — 20260911200000.
 *
 * One row per disclosure of a training record to an expedition company. Every
 * field is written by `open_enquiry_with_readiness` and then frozen by
 * `readiness_shares_guard`; the app inserts nothing here directly and holds no
 * insert grant, which is why the `Insert` side of the table entry below is
 * `never`.
 *
 * `disclosed_text` IS THE DISCLOSURE, not a description of it. Read it back and
 * render it; do not rebuild it from the athlete's current figures, which have
 * moved on since.
 */
export type ReadinessShare = {
  id: string;
  created_at: string;
  user_id: string;
  enquiry_id: string;
  /** NULL when the enquiry named a mountain and no company. Never a placeholder. */
  company_id: string | null;
  disclosed_text: string;
  measured_lines: number;
  reported_lines: number;
  /** True on every row ICEFALL has written. See `enquiries/operatorDisclosurePolicy.ts`. */
  vitals_withheld: boolean;
  consent_event_seq: number;
  /** NULL means in force. A date means withdrawn, and withdrawal is once-only. */
  revoked_at: string | null;
};

/**
 * `public.live_operator_companies` — a VIEW, and the whole operator directory
 * this app is permitted to see.
 *
 * Name and slug only. `companies` itself is unreadable to an athlete
 * (`companies_select` is staff-or-member), and the view deliberately omits
 * `verification_status` and `documents_checked_at`: printing "verified" beside
 * a business in a consumer app is a claim about somebody's company that
 * ICEFALL's own schema says means only that documents were looked at.
 *
 * EMPTY IS THE ORDINARY STATE. A company appears here only once it has
 * published a live product.
 */
export type LiveOperatorCompany = {
  id: string;
  slug: string;
  name: string;
};

/**
 * What `open_enquiry_with_readiness` returns.
 *
 * `share` IS shown — unlike the enquiry uuid, which `EnquiryOpened` explains is
 * a fabricated receipt. The difference is use: a share id is what a withdrawal
 * needs, the athlete never types it, and their own list of disclosures is where
 * it comes from.
 *
 * `delivered_to_company` is false when the enquiry named a mountain and no
 * company — which means the disclosure is held at the ICEFALL desk and can
 * never reach an operator. It is not "pending", and a screen must not draw it
 * as though it were.
 */
export type ReadinessShareOpened = {
  ok: true;
  share: string;
  delivered_to_company: boolean;
};

/** What `readiness_share_revoke` returns. See `enquiries/operatorShare.ts`. */
export type ReadinessShareRevoked = {
  ok: true;
  /** Already withdrawn before this call. Not an error and not a second one. */
  already: boolean;
  /**
   * ICEFALL had already handed the enquiry to the company. NOT a failure — the
   * fact that decides which of two true sentences a screen shows.
   */
  seen_by_company: boolean;
};

type Table<Row, Insert = Partial<Row>, Update = Partial<Row>> = {
  Row: Row;
  Insert: Insert;
  Update: Update;
  Relationships: [];
};

export type Database = {
  public: {
    Tables: {
      profiles: Table<Profile, Pick<Profile, "id" | "display_name">>;
      athlete_profiles: Table<AthleteProfile, Pick<AthleteProfile, "id"> & Partial<AthleteProfile>>;
      guide_profiles: Table<GuideProfile, Pick<GuideProfile, "id"> & Partial<GuideProfile>>;
      operator_profiles: Table<
        OperatorProfile,
        Pick<OperatorProfile, "id" | "company_name"> & Partial<OperatorProfile>
      >;
      threads: Table<Thread, Pick<Thread, "created_by"> & Partial<Thread>>;
      thread_participants: Table<
        ThreadParticipant,
        Pick<ThreadParticipant, "thread_id" | "profile_id">
      >;
      messages: Table<Message, Pick<Message, "thread_id" | "sender_id"> & Partial<Message>>;
      /*
       * READ-ONLY, AND THE TYPE SAYS SO. `never` on the Insert and Update sides
       * of all four: this app holds no write grant on the marketplace, and the
       * disclosure record is written only by `open_enquiry_with_readiness` and
       * amended only by `readiness_share_revoke`. A `Partial<Row>` default here
       * would compile an `.insert()` that the database then refuses at runtime,
       * which is the wrong place to find out.
       */
      products: Table<MarketplaceProduct, never, never>;
      product_destinations: Table<ProductDestination, never, never>;
      readiness_shares: Table<ReadinessShare, never, never>;
    };
    Views: {
      /** See `LiveOperatorCompany`. Select-only; a view has no insert side. */
      live_operator_companies: Table<LiveOperatorCompany, never, never>;
    };
    Functions: {
      is_admin: { Args: Record<never, never>; Returns: boolean };
      my_role: { Args: Record<never, never>; Returns: IcefallRole };
      is_thread_participant: { Args: { t: string }; Returns: boolean };
      /**
       * MESSAGING. Three calls, and none of them decides who may talk to whom —
       * `messages_insert` does, with all four of its conjuncts (yourself, a
       * thread you are in, no block between you, and decision 19: a guide or
       * operator may reply but never open).
       *
       * `send_message` is SECURITY INVOKER on purpose, so the insert inside it
       * passes through that policy exactly as a raw insert would. What it adds
       * is what a policy cannot: an IDEMPOTENT RESEND — a retry carrying the
       * same `p_client_id` returns the message that already arrived instead of
       * a duplicate — and it stamps the sender's own read receipt, so your own
       * message can never sit unread at you.
       *
       * `mark_thread_read` returns the new stamp, or NULL when the caller is
       * not a participant — which says nothing about whether the thread exists.
       *
       * `open_direct_thread` is NOT DEPLOYED YET. It is written in
       * 20260908090000_direct_threads.sql and declared here so the one call
       * site type-checks; a server without it answers PGRST202, which
       * `classifyBackendError` reports as "not-provisioned" and
       * `messaging/send.ts` handles by searching and creating under the
       * existing policies instead.
       */
      send_message: {
        Args: {
          p_thread_id: string;
          p_body: string;
          p_client_id?: string | null;
          p_kind?: MessageKind;
          p_attachment_path?: string | null;
          p_attachment_meta?: Record<string, unknown> | null;
        };
        Returns: Message;
      };
      mark_thread_read: { Args: { p_thread_id: string }; Returns: string | null };
      /** The thread id, or NULL when the two are in a block. */
      open_direct_thread: { Args: { p_other: string }; Returns: string | null };
      /**
       * ADVISORY. Stale the moment it returns — two people can both be told a
       * name is free. `claim_username` is the one that decides.
       */
      username_available: { Args: { candidate: string }; Returns: UsernameVerdict };
      /**
       * The only call that decides. Converts a unique-violation into
       * `{ok:false, reason:'taken'}` rather than raising, so no caller has to
       * read a Postgres error string.
       */
      claim_username: { Args: { candidate: string }; Returns: UsernameVerdict };
      set_my_location: {
        Args: { p_label: string | null; p_country: string | null };
        Returns: { ok: boolean; reason?: string };
      };
      /**
       * Open a support ticket. The ONLY sanctioned path for a signed-in person.
       *
       * NO ARGUMENT FOR WHO IS ASKING, AND THAT IS THE DESIGN. The function
       * derives the requester from `auth.uid()` — company, then guide, then
       * staff, then athlete — and stamps `requester_kind` on the row. A caller
       * cannot pass one, so a mis-tapped chooser cannot route a climber's
       * problem into the operator queue.
       *
       * `execute` is granted to `authenticated` only. An anonymous call is
       * refused at the GRANT and returns `42501 permission denied for function`
       * without ever reaching the body's own `not signed in` check — so a
       * caller that surfaces `error.message` shows a Postgres permission string
       * to a climber. Handle 42501 as "signed out"; see `support/tickets.ts`.
       *
       * `p_type` is NOT validated here. It goes straight into the INSERT and is
       * caught by `support_tickets_type_check`, so an unknown value returns a
       * constraint violation rather than anything readable.
       */
      accept_invitations: {
        Args: Record<string, never>;
        Returns: number;
      };
      open_support_ticket: {
        Args: {
          p_subject: string;
          p_body: string;
          p_type?: SupportTicketType;
          p_origin_app?: SupportOriginApp;
          p_origin_screen?: string | null;
        };
        Returns: SupportTicketOpened;
      };
      /**
       * HEALTH-DATA CONSENT. Three calls, and the split matters.
       *
       * `health_consent_wording_in_force` hands back the sentence to PUT ON THE
       * SCREEN. `health_record_consent` takes no version: it stamps whatever is
       * in force at write time, so a stale build cannot record agreement to
       * words nobody was shown. `health_my_consent` reads back the decision
       * with the frozen sentence it was made against.
       *
       * `p_decision` of 'withdrawn' or 'declined' ON THE 'health-metrics'
       * PURPOSE deletes every stored measurement inside the same transaction.
       * That is not a side effect to be surprised by — it is the erasure
       * Article 17 requires, placed where a caller cannot forget it.
       *
       * SCOPED TO THAT PURPOSE BY 20260911200000, and it used to be scoped to
       * nothing. While one purpose existed the difference was invisible; the
       * moment a second one did ('readiness-to-operator'), declining to send
       * training figures to an expedition company would have destroyed four
       * hundred days of the same person's sleep and heart-rate history, on a
       * screen that never mentioned a ring. Other purposes record the decision
       * and delete nothing.
       */
      health_consent_wording_in_force: {
        Args: { p_purpose: string };
        Returns: { version: string; wording: string }[];
      };
      health_record_consent: {
        Args: { p_purpose: string; p_decision: string; p_route?: string };
        Returns: number;
      };
      health_my_consent: {
        Args: { p_purpose: string };
        Returns: {
          decision: string;
          version: string | null;
          wording: string | null;
          recorded_at: string;
        }[];
      };
      open_enquiry: {
        Args: {
          p_body: string;
          p_product_id?: string | null;
          /**
           * TEXT, not a uuid. Mountains and treks are not tables — they resolve
           * through `destinations`, which is why this one is a slug.
           */
          p_destination_id?: string | null;
          p_company_id?: string | null;
          p_origin_app?: SupportOriginApp;
          p_origin_screen?: string | null;
        };
        Returns: EnquiryOpened;
      };
      /**
       * READINESS TO AN OPERATOR — 20260911200000.
       *
       * ONE CALL, ONE TRANSACTION: the enquiry, the per-share consent decision
       * and the disclosure record. Deliberately not three client calls — a
       * client that sent the enquiry and then failed to record the consent
       * would have disclosed under no permission, and one that recorded consent
       * and failed to send would hold a grant for a disclosure that never
       * happened. Both are wrong records of the same event.
       *
       * `p_readiness_text` IS THE CONSENTED TEXT. The server does not rebuild
       * it and must not: the only text anybody agreed to is the text that was
       * on the screen, and this argument is how it reaches the record.
       *
       * `p_vitals_withheld` MAY ONLY BE TRUE. The function raises on false —
       * today's consent wording promises wearable readings are not included, so
       * a client asserting otherwise would be disclosing under a sentence that
       * says the opposite. It is a parameter rather than an omission so that
       * the refusal is explicit at the call site. See
       * `enquiries/operatorDisclosurePolicy.ts`.
       */
      open_enquiry_with_readiness: {
        Args: {
          p_body: string;
          p_readiness_text: string;
          p_vitals_withheld?: boolean;
          p_product_id?: string | null;
          p_destination_id?: string | null;
          p_company_id?: string | null;
          p_origin_app?: SupportOriginApp;
          p_origin_screen?: string | null;
          p_measured_lines?: number;
          p_reported_lines?: number;
        };
        Returns: ReadinessShareOpened;
      };
      /**
       * Withdraw one disclosure: records a 'withdrawn' consent decision and
       * stamps the share, in the same transaction and for the same reason the
       * grant is atomic.
       *
       * IT DOES NOT UNSEND. A revoked share drops out of
       * `operator_readiness_shares` on the operator's next read; what they have
       * already opened is gone from ICEFALL's control. `seen_by_company` in the
       * result is how a screen tells the athlete which of those two happened,
       * and neither answer may be softened into the other.
       */
      readiness_share_revoke: {
        Args: { p_share_id: string };
        Returns: ReadinessShareRevoked;
      };
      /**
       * STRAVA. Two calls, and both are deliberately tiny.
       *
       * `strava_status` returns a SET — Postgres `returns table`, so supabase-js
       * hands back an array that is empty when nothing is connected. There is no
       * "connected: false" row; absence IS the answer, which is why `Returns` is
       * an array type here and every caller reads `data[0] ?? null`.
       *
       * IT CARRIES NO TOKEN, AND THIS TYPE IS PART OF THAT GUARANTEE. If a
       * future change adds `access_token` to the SQL, this shape is the second
       * place it would have to be added — see the header of
       * `icefall-supabase/migrations/20260907140000_strava_connection.sql`.
       *
       * `strava_disconnect` forgets the row and nothing else. It CANNOT
       * deauthorise at Strava — only the Edge Function can, holding the client
       * secret — so a caller that uses it alone has revoked ICEFALL's copy of a
       * token that Strava still honours. It exists for the one case the function
       * cannot serve: a token Strava has already revoked, where deauthorising
       * answers 401 forever and the row would otherwise be unremovable.
       */
      strava_status: {
        Args: Record<never, never>;
        Returns: {
          connected: boolean;
          /** NULL when Strava's token response did not identify the athlete. */
          athlete_id: number | null;
          athlete_username: string | null;
          scope: string;
          connected_at: string;
        }[];
      };
      strava_disconnect: { Args: Record<never, never>; Returns: undefined };
      /**
       * WATCH ACCOUNTS (COROS, Polar, Suunto, Garmin). Same two-call shape as
       * `strava_status` / `strava_disconnect`, generalised to a table because
       * a person can connect more than one watch service at once.
       *
       * `watch_status` returns a SET — one row per connected provider, empty
       * when nothing is connected. Absence IS the answer, same as Strava:
       * there is no `connected: false` row, and it carries no token material.
       *
       * `watch_disconnect` forgets one row, by provider. It CANNOT revoke at
       * the vendor — only the Edge Function can, holding the client
       * credentials — so it exists for the one case the function cannot
       * serve: a token the vendor has already revoked.
       */
      watch_status: {
        Args: Record<never, never>;
        Returns: {
          provider: "garmin" | "coros" | "suunto" | "polar";
          provider_user_id: string | null;
          account_label: string | null;
          scope: string;
          region: "eu" | "us" | null;
          connected_at: string;
        }[];
      };
      watch_disconnect: { Args: { p_provider: string }; Returns: undefined };

      /*
       * HEALTH ACCOUNTS — Polar, WHOOP, Withings, Oura (migration
       * 20260911120000, NOT YET APPLIED).
       *
       * `health_status` is the same shape and the same promise as
       * `watch_status`: a set, one row per connected provider, empty when
       * nothing is connected, and NO TOKEN MATERIAL. The tokens in
       * `health_connections` are ciphertext the database cannot decrypt, and
       * there is no policy that would let a client read them anyway — but this
       * return type is the boundary somebody would have to widen first, so it
       * is written narrowly on purpose.
       *
       * `health_disconnect` forgets one row, by provider. It CANNOT revoke at
       * the vendor and it does not delete stored measurements; the Edge
       * Function does the first and the consent-withdrawal path does the
       * second.
       */
      health_status: {
        Args: Record<never, never>;
        Returns: {
          provider: "polar" | "whoop" | "oura" | "withings";
          provider_user_id: string | null;
          account_label: string | null;
          scope: string;
          connected_at: string;
        }[];
      };
      health_disconnect: { Args: { p_provider: string }; Returns: undefined };

      /**
       * THE AMBASSADOR PROGRAMME (migration 20260912150000, NOT YET APPLIED).
       *
       * Called once, from `ChooseHandle`, the moment a brand-new account
       * exists — see `@/ambassador/capture`. Declared here, same as
       * `open_direct_thread` above, so that one call site type-checks; a
       * server without the migration answers PGRST202/42P01, which
       * `claimStoredAmbassadorReferral()` already treats as a tolerable,
       * silent failure — an ambassador code must never block somebody
       * finishing their own signup.
       *
       * Returns the `ambassador_referrals.id` that now exists (new or, on a
       * retried call, the one already recorded) as a uuid string.
       */
      record_ambassador_referral: { Args: { p_code: string }; Returns: string };

      /**
       * THE DURABLE, EMAIL-KEYED ATTRIBUTION PATH (migration 20260912160000,
       * NOT YET APPLIED). Called once alongside `record_ambassador_referral`
       * above, from `claimAmbassadorReferral()` in `@/ambassador/capture` —
       * see that file's header for why BOTH are called on every signup
       * completion. Looks up the signed-in account's own email (never a
       * client-supplied one) against `pending_ambassador_attributions`,
       * recorded earlier by an `icefall-web` waitlist signup, and applies it
       * via `record_ambassador_referral` if found.
       *
       * Takes no arguments. Returns the `ambassador_referrals.id` on a
       * successful attribution, or null when nothing was pending for this
       * email (the ordinary case for almost every signup) — a null is not an
       * error and must not be shown as one. Same tolerant-of-missing-
       * migration posture as the RPC above.
       */
      claim_pending_ambassador_attribution: { Args: Record<never, never>; Returns: string | null };
    };
    Enums: {
      icefall_role: IcefallRole;
    };
    CompositeTypes: Record<never, never>;
  };
};
