import { Link } from "react-router-dom";
import { ChevronLeft } from "lucide-react";
import { Rise, Screen, Stagger } from "@/components/layout/chrome";
import { Card } from "@/components/ui/primitives";
import { Notice } from "@/components/guide";
import { PersonAvatar, Photo } from "@/components/Photo";
import { fromDayRate, listing, offeredRoutes } from "@/domain/listing";
import { whatIsMissing } from "@/data/listingStore";
import { visibleApplication, eur } from "@/data/demo";
import { canListPublicly, effectiveStatus, verificationSentence } from "@/data/model";

/**
 * PREVIEW — the listing as a climber would read it.
 *
 * THIS IS THE HONEST HALF OF LETTING A GUIDE WRITE THEIR OWN LISTING. They are
 * describing themselves to somebody who will follow them onto glaciated ground,
 * so they should be able to see exactly what that person sees — including what
 * is MISSING, because an incomplete listing is not persuasive, it is unsafe to
 * book against.
 *
 * IT SHOWS WHAT ICEFALL WOULD SAY, NOT WHAT THE GUIDE WISHES IT SAID. The
 * verification sentence is the real one, generated by the same function the
 * client-facing surface will use, so a guide cannot preview a badge they have
 * not earned.
 *
 * NO RATING, NO REVIEW COUNT, NO SUMMIT TOTAL. Those exist on the guide's own
 * dashboard as owner-approved placeholders; putting them here would be
 * rehearsing a claim to a climber, which is the one audience the doctrine is
 * strictest about.
 */
export default function Preview() {
  const APPLICATION = visibleApplication();
  const l = listing();
  const p = l.profile;
  const offered = offeredRoutes();
  const from = fromDayRate();
  const status = effectiveStatus(APPLICATION);
  const listed = canListPublicly(APPLICATION);
  const missing = whatIsMissing(l, status === "approved");

  if (!p) {
    return (
      <Screen>
        <div className="pt-8">
          <Link to="/profile" className="inline-flex items-center gap-1 text-[12.5px] text-mist">
            <ChevronLeft size={16} strokeWidth={1.7} /> Profile
          </Link>
          <Card className="mt-5">
            <p className="text-[12.5px] text-mist">
              There is no listing on this device to preview.
            </p>
          </Card>
        </div>
      </Screen>
    );
  }

  return (
    <Screen padded={false}>
      <Stagger>
        <Rise className="relative">
          <Photo peak={p.heroPeak} alt="" className="h-44 w-full" rounded="rounded-none" />
          <div className="scrim-bottom absolute inset-x-0 bottom-0 h-28" />
          <Link
            to="/profile"
            aria-label="Back"
            className="absolute left-4 top-6 grid h-9 w-9 place-items-center rounded-full bg-obsidian/70 text-snow backdrop-blur"
          >
            <ChevronLeft size={20} strokeWidth={1.8} />
          </Link>
          <span className="absolute right-4 top-6 rounded-pill border border-hairline-strong bg-obsidian/70 px-3 py-1.5 text-[11px] text-mist backdrop-blur">
            As a climber sees it
          </span>
        </Rise>

        <Rise className="px-5 pt-4">
          <div className="flex items-start gap-3.5">
            <PersonAvatar name={p.name} size={58} />
            <div className="min-w-0 flex-1">
              <h1 className="text-[19px] font-light leading-tight text-snow">{p.name}</h1>
              <p className="mt-0.5 text-[12.5px] text-mist">{p.title}</p>
              <p className="tnum mt-0.5 text-[11.5px] text-mist-dim">
                {p.basedIn}
                {p.yearsGuiding > 0 && ` · ${p.yearsGuiding} years guiding`}
              </p>
            </div>
          </div>
          {from !== null && (
            <p className="tnum mt-3.5 text-[15px] text-snow">
              From {eur(from)} <span className="text-[12px] text-mist-dim">a day</span>
            </p>
          )}
        </Rise>

        {!listed && (
          <Rise className="px-5 pt-4">
            <Notice tone="alert">
              This is how you would appear. Your listing is not being shown to climbers right now —
              see Checks for what is outstanding.
            </Notice>
          </Rise>
        )}

        <Rise className="px-5 pt-5">
          <p className="section-label">About</p>
          <Card className="mt-3">
            <p className="text-[12.5px] leading-relaxed text-mist">{p.bio}</p>
            {p.languages.length > 0 && (
              <p className="mt-3 border-t border-hairline pt-3 text-[11.5px] text-mist-dim">
                Speaks {p.languages.join(", ")}
              </p>
            )}
          </Card>
        </Rise>

        <Rise className="px-5 pt-5">
          <p className="section-label">What {p.name.split(" ")[0]} guides</p>
          <div className="mt-3 space-y-2.5">
            {offered.map((m) => (
              <Card key={`${m.kind}:${m.routeId}`}>
                <div className="flex items-center gap-3.5">
                  <Photo
                    peak={m.routeId}
                    kind={m.photoKind}
                    alt=""
                    className="h-14 w-14 shrink-0"
                  />
                  <div className="min-w-0 flex-1">
                    <p className="text-[14px] leading-snug text-snow">{m.name}</p>
                    <p className="mt-0.5 truncate text-[11.5px] text-mist">{m.routes}</p>
                    <p className="tnum mt-1 text-[11.5px] text-mist-dim">
                      {m.grade} · {m.typicalDays} days · {eur(m.dayRateEur)}/day
                    </p>
                  </div>
                </div>
                <div className="mt-3 border-t border-hairline pt-3">
                  <p className="section-label">You must already be able to</p>
                  <p className="mt-1.5 text-[12px] leading-relaxed text-mist">{m.requires}</p>
                </div>
              </Card>
            ))}
            {offered.length === 0 && (
              <Card>
                <p className="py-3 text-center text-[12.5px] text-mist-dim">Nothing listed yet.</p>
              </Card>
            )}
          </div>
        </Rise>

        <Rise className="px-5 pt-5">
          <p className="section-label">What ICEFALL has checked</p>
          <Card className="mt-3">
            <p className="text-[12.5px] leading-relaxed text-mist">
              {verificationSentence(APPLICATION)}
            </p>
          </Card>
        </Rise>

        {missing.length > 0 && (
          <Rise className="px-5 pb-3 pt-5">
            <Notice tone="alert">
              <p className="text-snow">A climber would not see a complete listing</p>
              <p className="mt-1.5">Still missing: {missing.join(", ")}.</p>
            </Notice>
          </Rise>
        )}
      </Stagger>
    </Screen>
  );
}
